#if defined(_MSC_VER)
        #pragma warning (disable:4018) // 'expression' : signed/unsigned mismatch
        #pragma warning (disable:4065) // switch statement contains 'default' but no 'case' labels
        #pragma warning (disable:4146) // unary minus operator applied to unsigned type, result still unsigned
        #pragma warning (disable:4244) // 'conversion' conversion from 'type1' to 'type2', possible loss of data
        #pragma warning (disable:4251) // 'identifier' : class 'type' needs to have dll-interface to be used byclient of class 'type2'
        #pragma warning (disable:4267) // 'var' : conversion from 'size_t' to 'type', possible loss of data
        #pragma warning (disable:4305) // 'identifier' : truncation from 'type1' to 'type2'
        #pragma warning (disable:4307) // 'operator' : integral constant overflow
        #pragma warning (disable:4309) // 'conversion' : truncation of constant value
        #pragma warning (disable:4334) // 'operator' : result of 32-bit shift implicitly converted to 64 bits (was64bit shift intended?)
        #pragma warning (disable:4355) // 'this' : used in base member initializer list
        #pragma warning (disable:4506) // no definition for inline function 'function'
        #pragma warning (disable:4800) // 'type' : forcing value to bool 'true' or 'false' (performance warning)
		 #pragma warning (disable:4946) // reinterpret_cast used between related classes: 'class1' and 'class2'
        #pragma warning (disable:4996) // The compiler encountered a deprecated declaration.
        #pragma warning (disable:4125) // decimal digit terminates octal escape sequence
#endif

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: CommonPacket.proto

#include "CommonPacket.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG

namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = _pb::internal;

namespace Protocol {
PROTOBUF_CONSTEXPR C2S_ReplicatedServerTimeStamp::C2S_ReplicatedServerTimeStamp(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.utc_time_)*/int64_t{0}
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct C2S_ReplicatedServerTimeStampDefaultTypeInternal {
  PROTOBUF_CONSTEXPR C2S_ReplicatedServerTimeStampDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~C2S_ReplicatedServerTimeStampDefaultTypeInternal() {}
  union {
    C2S_ReplicatedServerTimeStamp _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 C2S_ReplicatedServerTimeStampDefaultTypeInternal _C2S_ReplicatedServerTimeStamp_default_instance_;
PROTOBUF_CONSTEXPR S2C_ReplicatedServerTimeStamp::S2C_ReplicatedServerTimeStamp(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.time_stamp_)*/int64_t{0}
  , /*decltype(_impl_.utc_time_)*/int64_t{0}
  , /*decltype(_impl_.rtt_)*/int64_t{0}
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct S2C_ReplicatedServerTimeStampDefaultTypeInternal {
  PROTOBUF_CONSTEXPR S2C_ReplicatedServerTimeStampDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~S2C_ReplicatedServerTimeStampDefaultTypeInternal() {}
  union {
    S2C_ReplicatedServerTimeStamp _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 S2C_ReplicatedServerTimeStampDefaultTypeInternal _S2C_ReplicatedServerTimeStamp_default_instance_;
PROTOBUF_CONSTEXPR C2S_TravelLevel::C2S_TravelLevel(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.level_)*/0
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct C2S_TravelLevelDefaultTypeInternal {
  PROTOBUF_CONSTEXPR C2S_TravelLevelDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~C2S_TravelLevelDefaultTypeInternal() {}
  union {
    C2S_TravelLevel _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 C2S_TravelLevelDefaultTypeInternal _C2S_TravelLevel_default_instance_;
PROTOBUF_CONSTEXPR S2C_TravelLevel::S2C_TravelLevel(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.error_)*/0
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct S2C_TravelLevelDefaultTypeInternal {
  PROTOBUF_CONSTEXPR S2C_TravelLevelDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~S2C_TravelLevelDefaultTypeInternal() {}
  union {
    S2C_TravelLevel _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 S2C_TravelLevelDefaultTypeInternal _S2C_TravelLevel_default_instance_;
PROTOBUF_CONSTEXPR C2S_TravelServer::C2S_TravelServer(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.token_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.global_id_)*/0
  , /*decltype(_impl_.character_id_)*/0
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct C2S_TravelServerDefaultTypeInternal {
  PROTOBUF_CONSTEXPR C2S_TravelServerDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~C2S_TravelServerDefaultTypeInternal() {}
  union {
    C2S_TravelServer _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 C2S_TravelServerDefaultTypeInternal _C2S_TravelServer_default_instance_;
PROTOBUF_CONSTEXPR S2C_TravelServer::S2C_TravelServer(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.token_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.travel_level_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.ip_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.server_id_)*/0
  , /*decltype(_impl_.port_)*/0
  , /*decltype(_impl_.error_)*/0
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct S2C_TravelServerDefaultTypeInternal {
  PROTOBUF_CONSTEXPR S2C_TravelServerDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~S2C_TravelServerDefaultTypeInternal() {}
  union {
    S2C_TravelServer _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 S2C_TravelServerDefaultTypeInternal _S2C_TravelServer_default_instance_;
}  // namespace Protocol
static ::_pb::Metadata file_level_metadata_CommonPacket_2eproto[6];
static constexpr ::_pb::EnumDescriptor const** file_level_enum_descriptors_CommonPacket_2eproto = nullptr;
static constexpr ::_pb::ServiceDescriptor const** file_level_service_descriptors_CommonPacket_2eproto = nullptr;

const uint32_t TableStruct_CommonPacket_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::Protocol::C2S_ReplicatedServerTimeStamp, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::Protocol::C2S_ReplicatedServerTimeStamp, _impl_.utc_time_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::Protocol::S2C_ReplicatedServerTimeStamp, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::Protocol::S2C_ReplicatedServerTimeStamp, _impl_.time_stamp_),
  PROTOBUF_FIELD_OFFSET(::Protocol::S2C_ReplicatedServerTimeStamp, _impl_.utc_time_),
  PROTOBUF_FIELD_OFFSET(::Protocol::S2C_ReplicatedServerTimeStamp, _impl_.rtt_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::Protocol::C2S_TravelLevel, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::Protocol::C2S_TravelLevel, _impl_.level_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::Protocol::S2C_TravelLevel, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::Protocol::S2C_TravelLevel, _impl_.error_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::Protocol::C2S_TravelServer, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::Protocol::C2S_TravelServer, _impl_.token_),
  PROTOBUF_FIELD_OFFSET(::Protocol::C2S_TravelServer, _impl_.global_id_),
  PROTOBUF_FIELD_OFFSET(::Protocol::C2S_TravelServer, _impl_.character_id_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::Protocol::S2C_TravelServer, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::Protocol::S2C_TravelServer, _impl_.token_),
  PROTOBUF_FIELD_OFFSET(::Protocol::S2C_TravelServer, _impl_.server_id_),
  PROTOBUF_FIELD_OFFSET(::Protocol::S2C_TravelServer, _impl_.travel_level_),
  PROTOBUF_FIELD_OFFSET(::Protocol::S2C_TravelServer, _impl_.ip_),
  PROTOBUF_FIELD_OFFSET(::Protocol::S2C_TravelServer, _impl_.port_),
  PROTOBUF_FIELD_OFFSET(::Protocol::S2C_TravelServer, _impl_.error_),
};
static const ::_pbi::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, -1, sizeof(::Protocol::C2S_ReplicatedServerTimeStamp)},
  { 7, -1, -1, sizeof(::Protocol::S2C_ReplicatedServerTimeStamp)},
  { 16, -1, -1, sizeof(::Protocol::C2S_TravelLevel)},
  { 23, -1, -1, sizeof(::Protocol::S2C_TravelLevel)},
  { 30, -1, -1, sizeof(::Protocol::C2S_TravelServer)},
  { 39, -1, -1, sizeof(::Protocol::S2C_TravelServer)},
};

static const ::_pb::Message* const file_default_instances[] = {
  &::Protocol::_C2S_ReplicatedServerTimeStamp_default_instance_._instance,
  &::Protocol::_S2C_ReplicatedServerTimeStamp_default_instance_._instance,
  &::Protocol::_C2S_TravelLevel_default_instance_._instance,
  &::Protocol::_S2C_TravelLevel_default_instance_._instance,
  &::Protocol::_C2S_TravelServer_default_instance_._instance,
  &::Protocol::_S2C_TravelServer_default_instance_._instance,
};

const char descriptor_table_protodef_CommonPacket_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\022CommonPacket.proto\022\010Protocol\"1\n\035C2S_Re"
  "plicatedServerTimeStamp\022\020\n\010utc_time\030\001 \001("
  "\003\"R\n\035S2C_ReplicatedServerTimeStamp\022\022\n\nti"
  "me_stamp\030\001 \001(\003\022\020\n\010utc_time\030\002 \001(\003\022\013\n\003rtt\030"
  "\003 \001(\003\" \n\017C2S_TravelLevel\022\r\n\005level\030\001 \001(\005\""
  " \n\017S2C_TravelLevel\022\r\n\005error\030\001 \001(\005\"J\n\020C2S"
  "_TravelServer\022\r\n\005token\030\001 \001(\014\022\021\n\tglobal_i"
  "d\030\002 \001(\005\022\024\n\014character_id\030\003 \001(\005\"s\n\020S2C_Tra"
  "velServer\022\r\n\005token\030\001 \001(\014\022\021\n\tserver_id\030\002 "
  "\001(\005\022\024\n\014travel_level\030\003 \001(\014\022\n\n\002ip\030\004 \001(\014\022\014\n"
  "\004port\030\005 \001(\005\022\r\n\005error\030\006 \001(\005b\006proto3"
  ;
static ::_pbi::once_flag descriptor_table_CommonPacket_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_CommonPacket_2eproto = {
    false, false, 434, descriptor_table_protodef_CommonPacket_2eproto,
    "CommonPacket.proto",
    &descriptor_table_CommonPacket_2eproto_once, nullptr, 0, 6,
    schemas, file_default_instances, TableStruct_CommonPacket_2eproto::offsets,
    file_level_metadata_CommonPacket_2eproto, file_level_enum_descriptors_CommonPacket_2eproto,
    file_level_service_descriptors_CommonPacket_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_CommonPacket_2eproto_getter() {
  return &descriptor_table_CommonPacket_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_CommonPacket_2eproto(&descriptor_table_CommonPacket_2eproto);
namespace Protocol {

// ===================================================================

class C2S_ReplicatedServerTimeStamp::_Internal {
 public:
};

C2S_ReplicatedServerTimeStamp::C2S_ReplicatedServerTimeStamp(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:Protocol.C2S_ReplicatedServerTimeStamp)
}
C2S_ReplicatedServerTimeStamp::C2S_ReplicatedServerTimeStamp(const C2S_ReplicatedServerTimeStamp& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  C2S_ReplicatedServerTimeStamp* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.utc_time_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _this->_impl_.utc_time_ = from._impl_.utc_time_;
  // @@protoc_insertion_point(copy_constructor:Protocol.C2S_ReplicatedServerTimeStamp)
}

inline void C2S_ReplicatedServerTimeStamp::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.utc_time_){int64_t{0}}
    , /*decltype(_impl_._cached_size_)*/{}
  };
}

C2S_ReplicatedServerTimeStamp::~C2S_ReplicatedServerTimeStamp() {
  // @@protoc_insertion_point(destructor:Protocol.C2S_ReplicatedServerTimeStamp)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void C2S_ReplicatedServerTimeStamp::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
}

void C2S_ReplicatedServerTimeStamp::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void C2S_ReplicatedServerTimeStamp::Clear() {
// @@protoc_insertion_point(message_clear_start:Protocol.C2S_ReplicatedServerTimeStamp)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.utc_time_ = int64_t{0};
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* C2S_ReplicatedServerTimeStamp::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // int64 utc_time = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          _impl_.utc_time_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* C2S_ReplicatedServerTimeStamp::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:Protocol.C2S_ReplicatedServerTimeStamp)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // int64 utc_time = 1;
  if (this->_internal_utc_time() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt64ToArray(1, this->_internal_utc_time(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:Protocol.C2S_ReplicatedServerTimeStamp)
  return target;
}

size_t C2S_ReplicatedServerTimeStamp::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:Protocol.C2S_ReplicatedServerTimeStamp)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // int64 utc_time = 1;
  if (this->_internal_utc_time() != 0) {
    total_size += ::_pbi::WireFormatLite::Int64SizePlusOne(this->_internal_utc_time());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData C2S_ReplicatedServerTimeStamp::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    C2S_ReplicatedServerTimeStamp::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*C2S_ReplicatedServerTimeStamp::GetClassData() const { return &_class_data_; }


void C2S_ReplicatedServerTimeStamp::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<C2S_ReplicatedServerTimeStamp*>(&to_msg);
  auto& from = static_cast<const C2S_ReplicatedServerTimeStamp&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:Protocol.C2S_ReplicatedServerTimeStamp)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_utc_time() != 0) {
    _this->_internal_set_utc_time(from._internal_utc_time());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void C2S_ReplicatedServerTimeStamp::CopyFrom(const C2S_ReplicatedServerTimeStamp& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:Protocol.C2S_ReplicatedServerTimeStamp)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool C2S_ReplicatedServerTimeStamp::IsInitialized() const {
  return true;
}

void C2S_ReplicatedServerTimeStamp::InternalSwap(C2S_ReplicatedServerTimeStamp* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_.utc_time_, other->_impl_.utc_time_);
}

::PROTOBUF_NAMESPACE_ID::Metadata C2S_ReplicatedServerTimeStamp::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_CommonPacket_2eproto_getter, &descriptor_table_CommonPacket_2eproto_once,
      file_level_metadata_CommonPacket_2eproto[0]);
}

// ===================================================================

class S2C_ReplicatedServerTimeStamp::_Internal {
 public:
};

S2C_ReplicatedServerTimeStamp::S2C_ReplicatedServerTimeStamp(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:Protocol.S2C_ReplicatedServerTimeStamp)
}
S2C_ReplicatedServerTimeStamp::S2C_ReplicatedServerTimeStamp(const S2C_ReplicatedServerTimeStamp& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  S2C_ReplicatedServerTimeStamp* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.time_stamp_){}
    , decltype(_impl_.utc_time_){}
    , decltype(_impl_.rtt_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::memcpy(&_impl_.time_stamp_, &from._impl_.time_stamp_,
    static_cast<size_t>(reinterpret_cast<char*>(&_impl_.rtt_) -
    reinterpret_cast<char*>(&_impl_.time_stamp_)) + sizeof(_impl_.rtt_));
  // @@protoc_insertion_point(copy_constructor:Protocol.S2C_ReplicatedServerTimeStamp)
}

inline void S2C_ReplicatedServerTimeStamp::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.time_stamp_){int64_t{0}}
    , decltype(_impl_.utc_time_){int64_t{0}}
    , decltype(_impl_.rtt_){int64_t{0}}
    , /*decltype(_impl_._cached_size_)*/{}
  };
}

S2C_ReplicatedServerTimeStamp::~S2C_ReplicatedServerTimeStamp() {
  // @@protoc_insertion_point(destructor:Protocol.S2C_ReplicatedServerTimeStamp)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void S2C_ReplicatedServerTimeStamp::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
}

void S2C_ReplicatedServerTimeStamp::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void S2C_ReplicatedServerTimeStamp::Clear() {
// @@protoc_insertion_point(message_clear_start:Protocol.S2C_ReplicatedServerTimeStamp)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::memset(&_impl_.time_stamp_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&_impl_.rtt_) -
      reinterpret_cast<char*>(&_impl_.time_stamp_)) + sizeof(_impl_.rtt_));
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* S2C_ReplicatedServerTimeStamp::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // int64 time_stamp = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          _impl_.time_stamp_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // int64 utc_time = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 16)) {
          _impl_.utc_time_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // int64 rtt = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 24)) {
          _impl_.rtt_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* S2C_ReplicatedServerTimeStamp::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:Protocol.S2C_ReplicatedServerTimeStamp)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // int64 time_stamp = 1;
  if (this->_internal_time_stamp() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt64ToArray(1, this->_internal_time_stamp(), target);
  }

  // int64 utc_time = 2;
  if (this->_internal_utc_time() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt64ToArray(2, this->_internal_utc_time(), target);
  }

  // int64 rtt = 3;
  if (this->_internal_rtt() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt64ToArray(3, this->_internal_rtt(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:Protocol.S2C_ReplicatedServerTimeStamp)
  return target;
}

size_t S2C_ReplicatedServerTimeStamp::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:Protocol.S2C_ReplicatedServerTimeStamp)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // int64 time_stamp = 1;
  if (this->_internal_time_stamp() != 0) {
    total_size += ::_pbi::WireFormatLite::Int64SizePlusOne(this->_internal_time_stamp());
  }

  // int64 utc_time = 2;
  if (this->_internal_utc_time() != 0) {
    total_size += ::_pbi::WireFormatLite::Int64SizePlusOne(this->_internal_utc_time());
  }

  // int64 rtt = 3;
  if (this->_internal_rtt() != 0) {
    total_size += ::_pbi::WireFormatLite::Int64SizePlusOne(this->_internal_rtt());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData S2C_ReplicatedServerTimeStamp::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    S2C_ReplicatedServerTimeStamp::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*S2C_ReplicatedServerTimeStamp::GetClassData() const { return &_class_data_; }


void S2C_ReplicatedServerTimeStamp::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<S2C_ReplicatedServerTimeStamp*>(&to_msg);
  auto& from = static_cast<const S2C_ReplicatedServerTimeStamp&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:Protocol.S2C_ReplicatedServerTimeStamp)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_time_stamp() != 0) {
    _this->_internal_set_time_stamp(from._internal_time_stamp());
  }
  if (from._internal_utc_time() != 0) {
    _this->_internal_set_utc_time(from._internal_utc_time());
  }
  if (from._internal_rtt() != 0) {
    _this->_internal_set_rtt(from._internal_rtt());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void S2C_ReplicatedServerTimeStamp::CopyFrom(const S2C_ReplicatedServerTimeStamp& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:Protocol.S2C_ReplicatedServerTimeStamp)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool S2C_ReplicatedServerTimeStamp::IsInitialized() const {
  return true;
}

void S2C_ReplicatedServerTimeStamp::InternalSwap(S2C_ReplicatedServerTimeStamp* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(S2C_ReplicatedServerTimeStamp, _impl_.rtt_)
      + sizeof(S2C_ReplicatedServerTimeStamp::_impl_.rtt_)
      - PROTOBUF_FIELD_OFFSET(S2C_ReplicatedServerTimeStamp, _impl_.time_stamp_)>(
          reinterpret_cast<char*>(&_impl_.time_stamp_),
          reinterpret_cast<char*>(&other->_impl_.time_stamp_));
}

::PROTOBUF_NAMESPACE_ID::Metadata S2C_ReplicatedServerTimeStamp::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_CommonPacket_2eproto_getter, &descriptor_table_CommonPacket_2eproto_once,
      file_level_metadata_CommonPacket_2eproto[1]);
}

// ===================================================================

class C2S_TravelLevel::_Internal {
 public:
};

C2S_TravelLevel::C2S_TravelLevel(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:Protocol.C2S_TravelLevel)
}
C2S_TravelLevel::C2S_TravelLevel(const C2S_TravelLevel& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  C2S_TravelLevel* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.level_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _this->_impl_.level_ = from._impl_.level_;
  // @@protoc_insertion_point(copy_constructor:Protocol.C2S_TravelLevel)
}

inline void C2S_TravelLevel::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.level_){0}
    , /*decltype(_impl_._cached_size_)*/{}
  };
}

C2S_TravelLevel::~C2S_TravelLevel() {
  // @@protoc_insertion_point(destructor:Protocol.C2S_TravelLevel)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void C2S_TravelLevel::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
}

void C2S_TravelLevel::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void C2S_TravelLevel::Clear() {
// @@protoc_insertion_point(message_clear_start:Protocol.C2S_TravelLevel)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.level_ = 0;
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* C2S_TravelLevel::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // int32 level = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          _impl_.level_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* C2S_TravelLevel::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:Protocol.C2S_TravelLevel)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // int32 level = 1;
  if (this->_internal_level() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt32ToArray(1, this->_internal_level(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:Protocol.C2S_TravelLevel)
  return target;
}

size_t C2S_TravelLevel::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:Protocol.C2S_TravelLevel)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // int32 level = 1;
  if (this->_internal_level() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(this->_internal_level());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData C2S_TravelLevel::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    C2S_TravelLevel::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*C2S_TravelLevel::GetClassData() const { return &_class_data_; }


void C2S_TravelLevel::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<C2S_TravelLevel*>(&to_msg);
  auto& from = static_cast<const C2S_TravelLevel&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:Protocol.C2S_TravelLevel)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_level() != 0) {
    _this->_internal_set_level(from._internal_level());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void C2S_TravelLevel::CopyFrom(const C2S_TravelLevel& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:Protocol.C2S_TravelLevel)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool C2S_TravelLevel::IsInitialized() const {
  return true;
}

void C2S_TravelLevel::InternalSwap(C2S_TravelLevel* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_.level_, other->_impl_.level_);
}

::PROTOBUF_NAMESPACE_ID::Metadata C2S_TravelLevel::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_CommonPacket_2eproto_getter, &descriptor_table_CommonPacket_2eproto_once,
      file_level_metadata_CommonPacket_2eproto[2]);
}

// ===================================================================

class S2C_TravelLevel::_Internal {
 public:
};

S2C_TravelLevel::S2C_TravelLevel(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:Protocol.S2C_TravelLevel)
}
S2C_TravelLevel::S2C_TravelLevel(const S2C_TravelLevel& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  S2C_TravelLevel* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.error_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _this->_impl_.error_ = from._impl_.error_;
  // @@protoc_insertion_point(copy_constructor:Protocol.S2C_TravelLevel)
}

inline void S2C_TravelLevel::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.error_){0}
    , /*decltype(_impl_._cached_size_)*/{}
  };
}

S2C_TravelLevel::~S2C_TravelLevel() {
  // @@protoc_insertion_point(destructor:Protocol.S2C_TravelLevel)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void S2C_TravelLevel::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
}

void S2C_TravelLevel::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void S2C_TravelLevel::Clear() {
// @@protoc_insertion_point(message_clear_start:Protocol.S2C_TravelLevel)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.error_ = 0;
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* S2C_TravelLevel::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // int32 error = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          _impl_.error_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* S2C_TravelLevel::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:Protocol.S2C_TravelLevel)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // int32 error = 1;
  if (this->_internal_error() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt32ToArray(1, this->_internal_error(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:Protocol.S2C_TravelLevel)
  return target;
}

size_t S2C_TravelLevel::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:Protocol.S2C_TravelLevel)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // int32 error = 1;
  if (this->_internal_error() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(this->_internal_error());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData S2C_TravelLevel::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    S2C_TravelLevel::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*S2C_TravelLevel::GetClassData() const { return &_class_data_; }


void S2C_TravelLevel::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<S2C_TravelLevel*>(&to_msg);
  auto& from = static_cast<const S2C_TravelLevel&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:Protocol.S2C_TravelLevel)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_error() != 0) {
    _this->_internal_set_error(from._internal_error());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void S2C_TravelLevel::CopyFrom(const S2C_TravelLevel& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:Protocol.S2C_TravelLevel)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool S2C_TravelLevel::IsInitialized() const {
  return true;
}

void S2C_TravelLevel::InternalSwap(S2C_TravelLevel* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_.error_, other->_impl_.error_);
}

::PROTOBUF_NAMESPACE_ID::Metadata S2C_TravelLevel::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_CommonPacket_2eproto_getter, &descriptor_table_CommonPacket_2eproto_once,
      file_level_metadata_CommonPacket_2eproto[3]);
}

// ===================================================================

class C2S_TravelServer::_Internal {
 public:
};

C2S_TravelServer::C2S_TravelServer(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:Protocol.C2S_TravelServer)
}
C2S_TravelServer::C2S_TravelServer(const C2S_TravelServer& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  C2S_TravelServer* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.token_){}
    , decltype(_impl_.global_id_){}
    , decltype(_impl_.character_id_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _impl_.token_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.token_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_token().empty()) {
    _this->_impl_.token_.Set(from._internal_token(), 
      _this->GetArenaForAllocation());
  }
  ::memcpy(&_impl_.global_id_, &from._impl_.global_id_,
    static_cast<size_t>(reinterpret_cast<char*>(&_impl_.character_id_) -
    reinterpret_cast<char*>(&_impl_.global_id_)) + sizeof(_impl_.character_id_));
  // @@protoc_insertion_point(copy_constructor:Protocol.C2S_TravelServer)
}

inline void C2S_TravelServer::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.token_){}
    , decltype(_impl_.global_id_){0}
    , decltype(_impl_.character_id_){0}
    , /*decltype(_impl_._cached_size_)*/{}
  };
  _impl_.token_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.token_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
}

C2S_TravelServer::~C2S_TravelServer() {
  // @@protoc_insertion_point(destructor:Protocol.C2S_TravelServer)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void C2S_TravelServer::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.token_.Destroy();
}

void C2S_TravelServer::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void C2S_TravelServer::Clear() {
// @@protoc_insertion_point(message_clear_start:Protocol.C2S_TravelServer)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.token_.ClearToEmpty();
  ::memset(&_impl_.global_id_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&_impl_.character_id_) -
      reinterpret_cast<char*>(&_impl_.global_id_)) + sizeof(_impl_.character_id_));
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* C2S_TravelServer::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // bytes token = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          auto str = _internal_mutable_token();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // int32 global_id = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 16)) {
          _impl_.global_id_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // int32 character_id = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 24)) {
          _impl_.character_id_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* C2S_TravelServer::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:Protocol.C2S_TravelServer)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // bytes token = 1;
  if (!this->_internal_token().empty()) {
    target = stream->WriteBytesMaybeAliased(
        1, this->_internal_token(), target);
  }

  // int32 global_id = 2;
  if (this->_internal_global_id() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt32ToArray(2, this->_internal_global_id(), target);
  }

  // int32 character_id = 3;
  if (this->_internal_character_id() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt32ToArray(3, this->_internal_character_id(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:Protocol.C2S_TravelServer)
  return target;
}

size_t C2S_TravelServer::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:Protocol.C2S_TravelServer)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // bytes token = 1;
  if (!this->_internal_token().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::BytesSize(
        this->_internal_token());
  }

  // int32 global_id = 2;
  if (this->_internal_global_id() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(this->_internal_global_id());
  }

  // int32 character_id = 3;
  if (this->_internal_character_id() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(this->_internal_character_id());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData C2S_TravelServer::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    C2S_TravelServer::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*C2S_TravelServer::GetClassData() const { return &_class_data_; }


void C2S_TravelServer::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<C2S_TravelServer*>(&to_msg);
  auto& from = static_cast<const C2S_TravelServer&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:Protocol.C2S_TravelServer)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_token().empty()) {
    _this->_internal_set_token(from._internal_token());
  }
  if (from._internal_global_id() != 0) {
    _this->_internal_set_global_id(from._internal_global_id());
  }
  if (from._internal_character_id() != 0) {
    _this->_internal_set_character_id(from._internal_character_id());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void C2S_TravelServer::CopyFrom(const C2S_TravelServer& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:Protocol.C2S_TravelServer)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool C2S_TravelServer::IsInitialized() const {
  return true;
}

void C2S_TravelServer::InternalSwap(C2S_TravelServer* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.token_, lhs_arena,
      &other->_impl_.token_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(C2S_TravelServer, _impl_.character_id_)
      + sizeof(C2S_TravelServer::_impl_.character_id_)
      - PROTOBUF_FIELD_OFFSET(C2S_TravelServer, _impl_.global_id_)>(
          reinterpret_cast<char*>(&_impl_.global_id_),
          reinterpret_cast<char*>(&other->_impl_.global_id_));
}

::PROTOBUF_NAMESPACE_ID::Metadata C2S_TravelServer::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_CommonPacket_2eproto_getter, &descriptor_table_CommonPacket_2eproto_once,
      file_level_metadata_CommonPacket_2eproto[4]);
}

// ===================================================================

class S2C_TravelServer::_Internal {
 public:
};

S2C_TravelServer::S2C_TravelServer(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:Protocol.S2C_TravelServer)
}
S2C_TravelServer::S2C_TravelServer(const S2C_TravelServer& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  S2C_TravelServer* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.token_){}
    , decltype(_impl_.travel_level_){}
    , decltype(_impl_.ip_){}
    , decltype(_impl_.server_id_){}
    , decltype(_impl_.port_){}
    , decltype(_impl_.error_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _impl_.token_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.token_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_token().empty()) {
    _this->_impl_.token_.Set(from._internal_token(), 
      _this->GetArenaForAllocation());
  }
  _impl_.travel_level_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.travel_level_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_travel_level().empty()) {
    _this->_impl_.travel_level_.Set(from._internal_travel_level(), 
      _this->GetArenaForAllocation());
  }
  _impl_.ip_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.ip_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_ip().empty()) {
    _this->_impl_.ip_.Set(from._internal_ip(), 
      _this->GetArenaForAllocation());
  }
  ::memcpy(&_impl_.server_id_, &from._impl_.server_id_,
    static_cast<size_t>(reinterpret_cast<char*>(&_impl_.error_) -
    reinterpret_cast<char*>(&_impl_.server_id_)) + sizeof(_impl_.error_));
  // @@protoc_insertion_point(copy_constructor:Protocol.S2C_TravelServer)
}

inline void S2C_TravelServer::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.token_){}
    , decltype(_impl_.travel_level_){}
    , decltype(_impl_.ip_){}
    , decltype(_impl_.server_id_){0}
    , decltype(_impl_.port_){0}
    , decltype(_impl_.error_){0}
    , /*decltype(_impl_._cached_size_)*/{}
  };
  _impl_.token_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.token_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.travel_level_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.travel_level_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.ip_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.ip_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
}

S2C_TravelServer::~S2C_TravelServer() {
  // @@protoc_insertion_point(destructor:Protocol.S2C_TravelServer)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void S2C_TravelServer::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.token_.Destroy();
  _impl_.travel_level_.Destroy();
  _impl_.ip_.Destroy();
}

void S2C_TravelServer::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void S2C_TravelServer::Clear() {
// @@protoc_insertion_point(message_clear_start:Protocol.S2C_TravelServer)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.token_.ClearToEmpty();
  _impl_.travel_level_.ClearToEmpty();
  _impl_.ip_.ClearToEmpty();
  ::memset(&_impl_.server_id_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&_impl_.error_) -
      reinterpret_cast<char*>(&_impl_.server_id_)) + sizeof(_impl_.error_));
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* S2C_TravelServer::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // bytes token = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          auto str = _internal_mutable_token();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // int32 server_id = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 16)) {
          _impl_.server_id_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // bytes travel_level = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 26)) {
          auto str = _internal_mutable_travel_level();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // bytes ip = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 34)) {
          auto str = _internal_mutable_ip();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // int32 port = 5;
      case 5:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 40)) {
          _impl_.port_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // int32 error = 6;
      case 6:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 48)) {
          _impl_.error_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* S2C_TravelServer::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:Protocol.S2C_TravelServer)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // bytes token = 1;
  if (!this->_internal_token().empty()) {
    target = stream->WriteBytesMaybeAliased(
        1, this->_internal_token(), target);
  }

  // int32 server_id = 2;
  if (this->_internal_server_id() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt32ToArray(2, this->_internal_server_id(), target);
  }

  // bytes travel_level = 3;
  if (!this->_internal_travel_level().empty()) {
    target = stream->WriteBytesMaybeAliased(
        3, this->_internal_travel_level(), target);
  }

  // bytes ip = 4;
  if (!this->_internal_ip().empty()) {
    target = stream->WriteBytesMaybeAliased(
        4, this->_internal_ip(), target);
  }

  // int32 port = 5;
  if (this->_internal_port() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt32ToArray(5, this->_internal_port(), target);
  }

  // int32 error = 6;
  if (this->_internal_error() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt32ToArray(6, this->_internal_error(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:Protocol.S2C_TravelServer)
  return target;
}

size_t S2C_TravelServer::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:Protocol.S2C_TravelServer)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // bytes token = 1;
  if (!this->_internal_token().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::BytesSize(
        this->_internal_token());
  }

  // bytes travel_level = 3;
  if (!this->_internal_travel_level().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::BytesSize(
        this->_internal_travel_level());
  }

  // bytes ip = 4;
  if (!this->_internal_ip().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::BytesSize(
        this->_internal_ip());
  }

  // int32 server_id = 2;
  if (this->_internal_server_id() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(this->_internal_server_id());
  }

  // int32 port = 5;
  if (this->_internal_port() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(this->_internal_port());
  }

  // int32 error = 6;
  if (this->_internal_error() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(this->_internal_error());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData S2C_TravelServer::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    S2C_TravelServer::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*S2C_TravelServer::GetClassData() const { return &_class_data_; }


void S2C_TravelServer::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<S2C_TravelServer*>(&to_msg);
  auto& from = static_cast<const S2C_TravelServer&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:Protocol.S2C_TravelServer)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_token().empty()) {
    _this->_internal_set_token(from._internal_token());
  }
  if (!from._internal_travel_level().empty()) {
    _this->_internal_set_travel_level(from._internal_travel_level());
  }
  if (!from._internal_ip().empty()) {
    _this->_internal_set_ip(from._internal_ip());
  }
  if (from._internal_server_id() != 0) {
    _this->_internal_set_server_id(from._internal_server_id());
  }
  if (from._internal_port() != 0) {
    _this->_internal_set_port(from._internal_port());
  }
  if (from._internal_error() != 0) {
    _this->_internal_set_error(from._internal_error());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void S2C_TravelServer::CopyFrom(const S2C_TravelServer& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:Protocol.S2C_TravelServer)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool S2C_TravelServer::IsInitialized() const {
  return true;
}

void S2C_TravelServer::InternalSwap(S2C_TravelServer* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.token_, lhs_arena,
      &other->_impl_.token_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.travel_level_, lhs_arena,
      &other->_impl_.travel_level_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.ip_, lhs_arena,
      &other->_impl_.ip_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(S2C_TravelServer, _impl_.error_)
      + sizeof(S2C_TravelServer::_impl_.error_)
      - PROTOBUF_FIELD_OFFSET(S2C_TravelServer, _impl_.server_id_)>(
          reinterpret_cast<char*>(&_impl_.server_id_),
          reinterpret_cast<char*>(&other->_impl_.server_id_));
}

::PROTOBUF_NAMESPACE_ID::Metadata S2C_TravelServer::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_CommonPacket_2eproto_getter, &descriptor_table_CommonPacket_2eproto_once,
      file_level_metadata_CommonPacket_2eproto[5]);
}

// @@protoc_insertion_point(namespace_scope)
}  // namespace Protocol
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::Protocol::C2S_ReplicatedServerTimeStamp*
Arena::CreateMaybeMessage< ::Protocol::C2S_ReplicatedServerTimeStamp >(Arena* arena) {
  return Arena::CreateMessageInternal< ::Protocol::C2S_ReplicatedServerTimeStamp >(arena);
}
template<> PROTOBUF_NOINLINE ::Protocol::S2C_ReplicatedServerTimeStamp*
Arena::CreateMaybeMessage< ::Protocol::S2C_ReplicatedServerTimeStamp >(Arena* arena) {
  return Arena::CreateMessageInternal< ::Protocol::S2C_ReplicatedServerTimeStamp >(arena);
}
template<> PROTOBUF_NOINLINE ::Protocol::C2S_TravelLevel*
Arena::CreateMaybeMessage< ::Protocol::C2S_TravelLevel >(Arena* arena) {
  return Arena::CreateMessageInternal< ::Protocol::C2S_TravelLevel >(arena);
}
template<> PROTOBUF_NOINLINE ::Protocol::S2C_TravelLevel*
Arena::CreateMaybeMessage< ::Protocol::S2C_TravelLevel >(Arena* arena) {
  return Arena::CreateMessageInternal< ::Protocol::S2C_TravelLevel >(arena);
}
template<> PROTOBUF_NOINLINE ::Protocol::C2S_TravelServer*
Arena::CreateMaybeMessage< ::Protocol::C2S_TravelServer >(Arena* arena) {
  return Arena::CreateMessageInternal< ::Protocol::C2S_TravelServer >(arena);
}
template<> PROTOBUF_NOINLINE ::Protocol::S2C_TravelServer*
Arena::CreateMaybeMessage< ::Protocol::S2C_TravelServer >(Arena* arena) {
  return Arena::CreateMessageInternal< ::Protocol::S2C_TravelServer >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
