#if defined(_MSC_VER)
		 #pragma warning (disable:4946) // reinterpret_cast used between related classes: 'class1' and 'class2'
#endif

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: PacketEnum.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_PacketEnum_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_PacketEnum_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021012 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/generated_enum_reflection.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_PacketEnum_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_PacketEnum_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_PacketEnum_2eproto;
PROTOBUF_NAMESPACE_OPEN
PROTOBUF_NAMESPACE_CLOSE
namespace Protocol {

enum EChat : int {
  Chat_Unspecified = 0,
  Chat_World = 1,
  Chat_Party = 2,
  Chat_Friend = 3,
  EChat_INT_MIN_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::min(),
  EChat_INT_MAX_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::max()
};
bool EChat_IsValid(int value);
constexpr EChat EChat_MIN = Chat_Unspecified;
constexpr EChat EChat_MAX = Chat_Friend;
constexpr int EChat_ARRAYSIZE = EChat_MAX + 1;

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* EChat_descriptor();
template<typename T>
inline const std::string& EChat_Name(T enum_t_value) {
  static_assert(::std::is_same<T, EChat>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function EChat_Name.");
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfEnum(
    EChat_descriptor(), enum_t_value);
}
inline bool EChat_Parse(
    ::PROTOBUF_NAMESPACE_ID::ConstStringParam name, EChat* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<EChat>(
    EChat_descriptor(), name, value);
}
enum ERace : int {
  Race_Unspecified = 0,
  Race_Men = 1,
  Race_Women = 2,
  Race_Orc = 3,
  ERace_INT_MIN_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::min(),
  ERace_INT_MAX_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::max()
};
bool ERace_IsValid(int value);
constexpr ERace ERace_MIN = Race_Unspecified;
constexpr ERace ERace_MAX = Race_Orc;
constexpr int ERace_ARRAYSIZE = ERace_MAX + 1;

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* ERace_descriptor();
template<typename T>
inline const std::string& ERace_Name(T enum_t_value) {
  static_assert(::std::is_same<T, ERace>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function ERace_Name.");
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfEnum(
    ERace_descriptor(), enum_t_value);
}
inline bool ERace_Parse(
    ::PROTOBUF_NAMESPACE_ID::ConstStringParam name, ERace* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<ERace>(
    ERace_descriptor(), name, value);
}
enum ECharacterClass : int {
  CClass_Unspecified = 0,
  CClass_Warrior = 1,
  CClass_Wizard = 2,
  ECharacterClass_INT_MIN_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::min(),
  ECharacterClass_INT_MAX_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::max()
};
bool ECharacterClass_IsValid(int value);
constexpr ECharacterClass ECharacterClass_MIN = CClass_Unspecified;
constexpr ECharacterClass ECharacterClass_MAX = CClass_Wizard;
constexpr int ECharacterClass_ARRAYSIZE = ECharacterClass_MAX + 1;

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* ECharacterClass_descriptor();
template<typename T>
inline const std::string& ECharacterClass_Name(T enum_t_value) {
  static_assert(::std::is_same<T, ECharacterClass>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function ECharacterClass_Name.");
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfEnum(
    ECharacterClass_descriptor(), enum_t_value);
}
inline bool ECharacterClass_Parse(
    ::PROTOBUF_NAMESPACE_ID::ConstStringParam name, ECharacterClass* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<ECharacterClass>(
    ECharacterClass_descriptor(), name, value);
}
enum ECharacterPart : int {
  Part_Unspecified = 0,
  Part_helmet = 1,
  Part_Shoulders = 2,
  Part_Chest = 3,
  Part_Bracers = 4,
  Part_Hands = 5,
  Part_Pants = 6,
  Part_Boots = 7,
  Part_Weapon_l = 8,
  Part_Weapon_r = 9,
  ECharacterPart_INT_MIN_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::min(),
  ECharacterPart_INT_MAX_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::max()
};
bool ECharacterPart_IsValid(int value);
constexpr ECharacterPart ECharacterPart_MIN = Part_Unspecified;
constexpr ECharacterPart ECharacterPart_MAX = Part_Weapon_r;
constexpr int ECharacterPart_ARRAYSIZE = ECharacterPart_MAX + 1;

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* ECharacterPart_descriptor();
template<typename T>
inline const std::string& ECharacterPart_Name(T enum_t_value) {
  static_assert(::std::is_same<T, ECharacterPart>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function ECharacterPart_Name.");
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfEnum(
    ECharacterPart_descriptor(), enum_t_value);
}
inline bool ECharacterPart_Parse(
    ::PROTOBUF_NAMESPACE_ID::ConstStringParam name, ECharacterPart* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<ECharacterPart>(
    ECharacterPart_descriptor(), name, value);
}
enum EEnemyState : int {
  State_Unspecified = 0,
  State_Spawn = 1,
  State_Idle = 2,
  State_Round = 3,
  State_Recovery = 4,
  State_Chase = 5,
  State_Attack = 6,
  State_CirticalAttack = 7,
  State_Hit = 8,
  State_CrowdControl = 9,
  State_Death = 10,
  EEnemyState_INT_MIN_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::min(),
  EEnemyState_INT_MAX_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::max()
};
bool EEnemyState_IsValid(int value);
constexpr EEnemyState EEnemyState_MIN = State_Unspecified;
constexpr EEnemyState EEnemyState_MAX = State_Death;
constexpr int EEnemyState_ARRAYSIZE = EEnemyState_MAX + 1;

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* EEnemyState_descriptor();
template<typename T>
inline const std::string& EEnemyState_Name(T enum_t_value) {
  static_assert(::std::is_same<T, EEnemyState>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function EEnemyState_Name.");
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfEnum(
    EEnemyState_descriptor(), enum_t_value);
}
inline bool EEnemyState_Parse(
    ::PROTOBUF_NAMESPACE_ID::ConstStringParam name, EEnemyState* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<EEnemyState>(
    EEnemyState_descriptor(), name, value);
}
enum EStatType : int {
  Stat_Unspecified = 0,
  Stat_ArmorPenetration = 1,
  Stat_AttackDamage = 2,
  Stat_AttackSpeed = 3,
  Stat_CriticalStrikeChance = 4,
  Stat_CirticalStrikeDamage = 5,
  Stat_LifeSteal = 6,
  Stat_AbilityPower = 7,
  Stat_MagePenetration = 8,
  Stat_Omnivamp = 9,
  Stat_PhysicalVamp = 10,
  Stat_Armor = 11,
  Stat_HealAndShieldPower = 12,
  Stat_Health = 13,
  Stat_HealthRegeneration = 14,
  Stat_MagicResistance = 15,
  Stat_Tenacity = 16,
  Stat_SlowResist = 17,
  Stat_AbilityHaste = 18,
  Stat_Mana = 19,
  Stat_ManaRegeneration = 20,
  Stat_MovementSpeed = 21,
  Stat_Range = 22,
  EStatType_INT_MIN_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::min(),
  EStatType_INT_MAX_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::max()
};
bool EStatType_IsValid(int value);
constexpr EStatType EStatType_MIN = Stat_Unspecified;
constexpr EStatType EStatType_MAX = Stat_Range;
constexpr int EStatType_ARRAYSIZE = EStatType_MAX + 1;

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* EStatType_descriptor();
template<typename T>
inline const std::string& EStatType_Name(T enum_t_value) {
  static_assert(::std::is_same<T, EStatType>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function EStatType_Name.");
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfEnum(
    EStatType_descriptor(), enum_t_value);
}
inline bool EStatType_Parse(
    ::PROTOBUF_NAMESPACE_ID::ConstStringParam name, EStatType* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<EStatType>(
    EStatType_descriptor(), name, value);
}
enum EActionType : int {
  Action_Unspecified = 0,
  Action_Item = 1,
  Action_Skill = 2,
  EActionType_INT_MIN_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::min(),
  EActionType_INT_MAX_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::max()
};
bool EActionType_IsValid(int value);
constexpr EActionType EActionType_MIN = Action_Unspecified;
constexpr EActionType EActionType_MAX = Action_Skill;
constexpr int EActionType_ARRAYSIZE = EActionType_MAX + 1;

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* EActionType_descriptor();
template<typename T>
inline const std::string& EActionType_Name(T enum_t_value) {
  static_assert(::std::is_same<T, EActionType>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function EActionType_Name.");
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfEnum(
    EActionType_descriptor(), enum_t_value);
}
inline bool EActionType_Parse(
    ::PROTOBUF_NAMESPACE_ID::ConstStringParam name, EActionType* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<EActionType>(
    EActionType_descriptor(), name, value);
}
// ===================================================================


// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace Protocol

PROTOBUF_NAMESPACE_OPEN

template <> struct is_proto_enum< ::Protocol::EChat> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::Protocol::EChat>() {
  return ::Protocol::EChat_descriptor();
}
template <> struct is_proto_enum< ::Protocol::ERace> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::Protocol::ERace>() {
  return ::Protocol::ERace_descriptor();
}
template <> struct is_proto_enum< ::Protocol::ECharacterClass> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::Protocol::ECharacterClass>() {
  return ::Protocol::ECharacterClass_descriptor();
}
template <> struct is_proto_enum< ::Protocol::ECharacterPart> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::Protocol::ECharacterPart>() {
  return ::Protocol::ECharacterPart_descriptor();
}
template <> struct is_proto_enum< ::Protocol::EEnemyState> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::Protocol::EEnemyState>() {
  return ::Protocol::EEnemyState_descriptor();
}
template <> struct is_proto_enum< ::Protocol::EStatType> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::Protocol::EStatType>() {
  return ::Protocol::EStatType_descriptor();
}
template <> struct is_proto_enum< ::Protocol::EActionType> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::Protocol::EActionType>() {
  return ::Protocol::EActionType_descriptor();
}

PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_PacketEnum_2eproto
