#if defined(_MSC_VER)
        #pragma warning (disable:4018) // 'expression' : signed/unsigned mismatch
        #pragma warning (disable:4065) // switch statement contains 'default' but no 'case' labels
        #pragma warning (disable:4146) // unary minus operator applied to unsigned type, result still unsigned
        #pragma warning (disable:4244) // 'conversion' conversion from 'type1' to 'type2', possible loss of data
        #pragma warning (disable:4251) // 'identifier' : class 'type' needs to have dll-interface to be used byclient of class 'type2'
        #pragma warning (disable:4267) // 'var' : conversion from 'size_t' to 'type', possible loss of data
        #pragma warning (disable:4305) // 'identifier' : truncation from 'type1' to 'type2'
        #pragma warning (disable:4307) // 'operator' : integral constant overflow
        #pragma warning (disable:4309) // 'conversion' : truncation of constant value
        #pragma warning (disable:4334) // 'operator' : result of 32-bit shift implicitly converted to 64 bits (was64bit shift intended?)
        #pragma warning (disable:4355) // 'this' : used in base member initializer list
        #pragma warning (disable:4506) // no definition for inline function 'function'
        #pragma warning (disable:4800) // 'type' : forcing value to bool 'true' or 'false' (performance warning)
		 #pragma warning (disable:4946) // reinterpret_cast used between related classes: 'class1' and 'class2'
        #pragma warning (disable:4996) // The compiler encountered a deprecated declaration.
        #pragma warning (disable:4125) // decimal digit terminates octal escape sequence
#endif

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: PacketEnum.proto

#include "PacketEnum.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG

namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = _pb::internal;

namespace Protocol {
}  // namespace Protocol
static const ::_pb::EnumDescriptor* file_level_enum_descriptors_PacketEnum_2eproto[5];
static constexpr ::_pb::ServiceDescriptor const** file_level_service_descriptors_PacketEnum_2eproto = nullptr;
const uint32_t TableStruct_PacketEnum_2eproto::offsets[1] = {};
static constexpr ::_pbi::MigrationSchema* schemas = nullptr;
static constexpr ::_pb::Message* const* file_default_instances = nullptr;

const char descriptor_table_protodef_PacketEnum_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\020PacketEnum.proto\022\010Protocol*I\n\005ERace\022\024\n"
  "\020Race_Unspecified\020\000\022\014\n\010Race_Men\020\001\022\016\n\nRac"
  "e_Women\020\002\022\014\n\010Race_Orc\020\003*P\n\017ECharacterCla"
  "ss\022\026\n\022CClass_Unspecified\020\000\022\022\n\016CClass_War"
  "rior\020\001\022\021\n\rCClass_Wizard\020\002*\303\001\n\016ECharacter"
  "Part\022\024\n\020Part_Unspecified\020\000\022\017\n\013Part_helme"
  "t\020\001\022\022\n\016Part_Shoulders\020\002\022\016\n\nPart_Chest\020\003\022"
  "\020\n\014Part_Bracers\020\004\022\016\n\nPart_Hands\020\005\022\016\n\nPar"
  "t_Pants\020\006\022\016\n\nPart_Boots\020\007\022\021\n\rPart_Weapon"
  "_l\020\010\022\021\n\rPart_Weapon_r\020\t*\337\001\n\013EEnemyState\022"
  "\025\n\021State_Unspecified\020\000\022\017\n\013State_Spawn\020\001\022"
  "\016\n\nState_Idle\020\002\022\017\n\013State_Round\020\003\022\022\n\016Stat"
  "e_Recovery\020\004\022\017\n\013State_Chase\020\005\022\020\n\014State_A"
  "ttack\020\006\022\030\n\024State_CirticalAttack\020\007\022\r\n\tSta"
  "te_Hit\020\010\022\026\n\022State_CrowdControl\020\t\022\017\n\013Stat"
  "e_Death\020\n*\234\004\n\tEStatType\022\024\n\020Stat_Unspecif"
  "ied\020\000\022\031\n\025Stat_ArmorPenetration\020\001\022\025\n\021Stat"
  "_AttackDamage\020\002\022\024\n\020Stat_AttackSpeed\020\003\022\035\n"
  "\031Stat_CriticalStrikeChance\020\004\022\035\n\031Stat_Cir"
  "ticalStrikeDamage\020\005\022\022\n\016Stat_LifeSteal\020\006\022"
  "\025\n\021Stat_AbilityPower\020\007\022\030\n\024Stat_MagePenet"
  "ration\020\010\022\021\n\rStat_Omnivamp\020\t\022\025\n\021Stat_Phys"
  "icalVamp\020\n\022\016\n\nStat_Armor\020\013\022\033\n\027Stat_HealA"
  "ndShieldPower\020\014\022\017\n\013Stat_Health\020\r\022\033\n\027Stat"
  "_HealthRegeneration\020\016\022\030\n\024Stat_MagicResis"
  "tance\020\017\022\021\n\rStat_Tenacity\020\020\022\023\n\017Stat_SlowR"
  "esist\020\021\022\025\n\021Stat_AbilityHaste\020\022\022\r\n\tStat_M"
  "ana\020\023\022\031\n\025Stat_ManaRegeneration\020\024\022\026\n\022Stat"
  "_MovementSpeed\020\025\022\016\n\nStat_Range\020\026b\006proto3"
  ;
static ::_pbi::once_flag descriptor_table_PacketEnum_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_PacketEnum_2eproto = {
    false, false, 1160, descriptor_table_protodef_PacketEnum_2eproto,
    "PacketEnum.proto",
    &descriptor_table_PacketEnum_2eproto_once, nullptr, 0, 0,
    schemas, file_default_instances, TableStruct_PacketEnum_2eproto::offsets,
    nullptr, file_level_enum_descriptors_PacketEnum_2eproto,
    file_level_service_descriptors_PacketEnum_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_PacketEnum_2eproto_getter() {
  return &descriptor_table_PacketEnum_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_PacketEnum_2eproto(&descriptor_table_PacketEnum_2eproto);
namespace Protocol {
const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* ERace_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_PacketEnum_2eproto);
  return file_level_enum_descriptors_PacketEnum_2eproto[0];
}
bool ERace_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
    case 3:
      return true;
    default:
      return false;
  }
}

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* ECharacterClass_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_PacketEnum_2eproto);
  return file_level_enum_descriptors_PacketEnum_2eproto[1];
}
bool ECharacterClass_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
      return true;
    default:
      return false;
  }
}

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* ECharacterPart_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_PacketEnum_2eproto);
  return file_level_enum_descriptors_PacketEnum_2eproto[2];
}
bool ECharacterPart_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
    case 3:
    case 4:
    case 5:
    case 6:
    case 7:
    case 8:
    case 9:
      return true;
    default:
      return false;
  }
}

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* EEnemyState_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_PacketEnum_2eproto);
  return file_level_enum_descriptors_PacketEnum_2eproto[3];
}
bool EEnemyState_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
    case 3:
    case 4:
    case 5:
    case 6:
    case 7:
    case 8:
    case 9:
    case 10:
      return true;
    default:
      return false;
  }
}

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* EStatType_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_PacketEnum_2eproto);
  return file_level_enum_descriptors_PacketEnum_2eproto[4];
}
bool EStatType_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
    case 3:
    case 4:
    case 5:
    case 6:
    case 7:
    case 8:
    case 9:
    case 10:
    case 11:
    case 12:
    case 13:
    case 14:
    case 15:
    case 16:
    case 17:
    case 18:
    case 19:
    case 20:
    case 21:
    case 22:
      return true;
    default:
      return false;
  }
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace Protocol
PROTOBUF_NAMESPACE_OPEN
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
