#if defined(_MSC_VER)
        #pragma warning (disable:4018) // 'expression' : signed/unsigned mismatch
        #pragma warning (disable:4065) // switch statement contains 'default' but no 'case' labels
        #pragma warning (disable:4146) // unary minus operator applied to unsigned type, result still unsigned
        #pragma warning (disable:4244) // 'conversion' conversion from 'type1' to 'type2', possible loss of data
        #pragma warning (disable:4251) // 'identifier' : class 'type' needs to have dll-interface to be used byclient of class 'type2'
        #pragma warning (disable:4267) // 'var' : conversion from 'size_t' to 'type', possible loss of data
        #pragma warning (disable:4305) // 'identifier' : truncation from 'type1' to 'type2'
        #pragma warning (disable:4307) // 'operator' : integral constant overflow
        #pragma warning (disable:4309) // 'conversion' : truncation of constant value
        #pragma warning (disable:4334) // 'operator' : result of 32-bit shift implicitly converted to 64 bits (was64bit shift intended?)
        #pragma warning (disable:4355) // 'this' : used in base member initializer list
        #pragma warning (disable:4506) // no definition for inline function 'function'
        #pragma warning (disable:4800) // 'type' : forcing value to bool 'true' or 'false' (performance warning)
		 #pragma warning (disable:4946) // reinterpret_cast used between related classes: 'class1' and 'class2'
        #pragma warning (disable:4996) // The compiler encountered a deprecated declaration.
        #pragma warning (disable:4125) // decimal digit terminates octal escape sequence
#endif

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: PacketStruct.proto

#include "PacketStruct.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG

namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = _pb::internal;

namespace Protocol {
PROTOBUF_CONSTEXPR SCharacterAppearance::SCharacterAppearance(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.race_)*/0
  , /*decltype(_impl_.character_class_)*/0
  , /*decltype(_impl_.seat_)*/0
  , /*decltype(_impl_.skin_color_)*/0
  , /*decltype(_impl_.hair_color_)*/0
  , /*decltype(_impl_.eye_color_)*/0
  , /*decltype(_impl_.eyebrow_color_)*/0
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct SCharacterAppearanceDefaultTypeInternal {
  PROTOBUF_CONSTEXPR SCharacterAppearanceDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~SCharacterAppearanceDefaultTypeInternal() {}
  union {
    SCharacterAppearance _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 SCharacterAppearanceDefaultTypeInternal _SCharacterAppearance_default_instance_;
PROTOBUF_CONSTEXPR SCharacterEqipment::SCharacterEqipment(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.hair_)*/0
  , /*decltype(_impl_.helmet_)*/0
  , /*decltype(_impl_.shoulders_)*/0
  , /*decltype(_impl_.chest_add_)*/0
  , /*decltype(_impl_.bracers_add_)*/0
  , /*decltype(_impl_.hands_add_)*/0
  , /*decltype(_impl_.pants_add_)*/0
  , /*decltype(_impl_.boots_)*/0
  , /*decltype(_impl_.weapon_l_)*/0
  , /*decltype(_impl_.weapon_r_)*/0
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct SCharacterEqipmentDefaultTypeInternal {
  PROTOBUF_CONSTEXPR SCharacterEqipmentDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~SCharacterEqipmentDefaultTypeInternal() {}
  union {
    SCharacterEqipment _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 SCharacterEqipmentDefaultTypeInternal _SCharacterEqipment_default_instance_;
}  // namespace Protocol
static ::_pb::Metadata file_level_metadata_PacketStruct_2eproto[2];
static constexpr ::_pb::EnumDescriptor const** file_level_enum_descriptors_PacketStruct_2eproto = nullptr;
static constexpr ::_pb::ServiceDescriptor const** file_level_service_descriptors_PacketStruct_2eproto = nullptr;

const uint32_t TableStruct_PacketStruct_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::Protocol::SCharacterAppearance, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::Protocol::SCharacterAppearance, _impl_.race_),
  PROTOBUF_FIELD_OFFSET(::Protocol::SCharacterAppearance, _impl_.character_class_),
  PROTOBUF_FIELD_OFFSET(::Protocol::SCharacterAppearance, _impl_.seat_),
  PROTOBUF_FIELD_OFFSET(::Protocol::SCharacterAppearance, _impl_.skin_color_),
  PROTOBUF_FIELD_OFFSET(::Protocol::SCharacterAppearance, _impl_.hair_color_),
  PROTOBUF_FIELD_OFFSET(::Protocol::SCharacterAppearance, _impl_.eye_color_),
  PROTOBUF_FIELD_OFFSET(::Protocol::SCharacterAppearance, _impl_.eyebrow_color_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::Protocol::SCharacterEqipment, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::Protocol::SCharacterEqipment, _impl_.hair_),
  PROTOBUF_FIELD_OFFSET(::Protocol::SCharacterEqipment, _impl_.helmet_),
  PROTOBUF_FIELD_OFFSET(::Protocol::SCharacterEqipment, _impl_.shoulders_),
  PROTOBUF_FIELD_OFFSET(::Protocol::SCharacterEqipment, _impl_.chest_add_),
  PROTOBUF_FIELD_OFFSET(::Protocol::SCharacterEqipment, _impl_.bracers_add_),
  PROTOBUF_FIELD_OFFSET(::Protocol::SCharacterEqipment, _impl_.hands_add_),
  PROTOBUF_FIELD_OFFSET(::Protocol::SCharacterEqipment, _impl_.pants_add_),
  PROTOBUF_FIELD_OFFSET(::Protocol::SCharacterEqipment, _impl_.boots_),
  PROTOBUF_FIELD_OFFSET(::Protocol::SCharacterEqipment, _impl_.weapon_l_),
  PROTOBUF_FIELD_OFFSET(::Protocol::SCharacterEqipment, _impl_.weapon_r_),
};
static const ::_pbi::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, -1, sizeof(::Protocol::SCharacterAppearance)},
  { 13, -1, -1, sizeof(::Protocol::SCharacterEqipment)},
};

static const ::_pb::Message* const file_default_instances[] = {
  &::Protocol::_SCharacterAppearance_default_instance_._instance,
  &::Protocol::_SCharacterEqipment_default_instance_._instance,
};

const char descriptor_table_protodef_PacketStruct_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\022PacketStruct.proto\022\010Protocol\032\020PacketEn"
  "um.proto\"\311\001\n\024SCharacterAppearance\022\035\n\004rac"
  "e\030\001 \001(\0162\017.Protocol.ERace\0222\n\017character_cl"
  "ass\030\002 \001(\0162\031.Protocol.ECharacterClass\022\014\n\004"
  "seat\030\003 \001(\005\022\022\n\nskin_color\030\004 \001(\005\022\022\n\nhair_c"
  "olor\030\005 \001(\005\022\021\n\teye_color\030\006 \001(\005\022\025\n\reyebrow"
  "_color\030\007 \001(\005\"\306\001\n\022SCharacterEqipment\022\014\n\004h"
  "air\030\001 \001(\005\022\016\n\006helmet\030\002 \001(\005\022\021\n\tshoulders\030\003"
  " \001(\005\022\021\n\tchest_add\030\004 \001(\005\022\023\n\013bracers_add\030\005"
  " \001(\005\022\021\n\thands_add\030\006 \001(\005\022\021\n\tpants_add\030\007 \001"
  "(\005\022\r\n\005boots\030\010 \001(\005\022\020\n\010weapon_l\030\t \001(\005\022\020\n\010w"
  "eapon_r\030\n \001(\005b\006proto3"
  ;
static const ::_pbi::DescriptorTable* const descriptor_table_PacketStruct_2eproto_deps[1] = {
  &::descriptor_table_PacketEnum_2eproto,
};
static ::_pbi::once_flag descriptor_table_PacketStruct_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_PacketStruct_2eproto = {
    false, false, 461, descriptor_table_protodef_PacketStruct_2eproto,
    "PacketStruct.proto",
    &descriptor_table_PacketStruct_2eproto_once, descriptor_table_PacketStruct_2eproto_deps, 1, 2,
    schemas, file_default_instances, TableStruct_PacketStruct_2eproto::offsets,
    file_level_metadata_PacketStruct_2eproto, file_level_enum_descriptors_PacketStruct_2eproto,
    file_level_service_descriptors_PacketStruct_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_PacketStruct_2eproto_getter() {
  return &descriptor_table_PacketStruct_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_PacketStruct_2eproto(&descriptor_table_PacketStruct_2eproto);
namespace Protocol {

// ===================================================================

class SCharacterAppearance::_Internal {
 public:
};

SCharacterAppearance::SCharacterAppearance(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:Protocol.SCharacterAppearance)
}
SCharacterAppearance::SCharacterAppearance(const SCharacterAppearance& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  SCharacterAppearance* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.race_){}
    , decltype(_impl_.character_class_){}
    , decltype(_impl_.seat_){}
    , decltype(_impl_.skin_color_){}
    , decltype(_impl_.hair_color_){}
    , decltype(_impl_.eye_color_){}
    , decltype(_impl_.eyebrow_color_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::memcpy(&_impl_.race_, &from._impl_.race_,
    static_cast<size_t>(reinterpret_cast<char*>(&_impl_.eyebrow_color_) -
    reinterpret_cast<char*>(&_impl_.race_)) + sizeof(_impl_.eyebrow_color_));
  // @@protoc_insertion_point(copy_constructor:Protocol.SCharacterAppearance)
}

inline void SCharacterAppearance::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.race_){0}
    , decltype(_impl_.character_class_){0}
    , decltype(_impl_.seat_){0}
    , decltype(_impl_.skin_color_){0}
    , decltype(_impl_.hair_color_){0}
    , decltype(_impl_.eye_color_){0}
    , decltype(_impl_.eyebrow_color_){0}
    , /*decltype(_impl_._cached_size_)*/{}
  };
}

SCharacterAppearance::~SCharacterAppearance() {
  // @@protoc_insertion_point(destructor:Protocol.SCharacterAppearance)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void SCharacterAppearance::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
}

void SCharacterAppearance::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void SCharacterAppearance::Clear() {
// @@protoc_insertion_point(message_clear_start:Protocol.SCharacterAppearance)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::memset(&_impl_.race_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&_impl_.eyebrow_color_) -
      reinterpret_cast<char*>(&_impl_.race_)) + sizeof(_impl_.eyebrow_color_));
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* SCharacterAppearance::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // .Protocol.ERace race = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          uint64_t val = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
          _internal_set_race(static_cast<::Protocol::ERace>(val));
        } else
          goto handle_unusual;
        continue;
      // .Protocol.ECharacterClass character_class = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 16)) {
          uint64_t val = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
          _internal_set_character_class(static_cast<::Protocol::ECharacterClass>(val));
        } else
          goto handle_unusual;
        continue;
      // int32 seat = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 24)) {
          _impl_.seat_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // int32 skin_color = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 32)) {
          _impl_.skin_color_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // int32 hair_color = 5;
      case 5:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 40)) {
          _impl_.hair_color_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // int32 eye_color = 6;
      case 6:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 48)) {
          _impl_.eye_color_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // int32 eyebrow_color = 7;
      case 7:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 56)) {
          _impl_.eyebrow_color_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* SCharacterAppearance::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:Protocol.SCharacterAppearance)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // .Protocol.ERace race = 1;
  if (this->_internal_race() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteEnumToArray(
      1, this->_internal_race(), target);
  }

  // .Protocol.ECharacterClass character_class = 2;
  if (this->_internal_character_class() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteEnumToArray(
      2, this->_internal_character_class(), target);
  }

  // int32 seat = 3;
  if (this->_internal_seat() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt32ToArray(3, this->_internal_seat(), target);
  }

  // int32 skin_color = 4;
  if (this->_internal_skin_color() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt32ToArray(4, this->_internal_skin_color(), target);
  }

  // int32 hair_color = 5;
  if (this->_internal_hair_color() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt32ToArray(5, this->_internal_hair_color(), target);
  }

  // int32 eye_color = 6;
  if (this->_internal_eye_color() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt32ToArray(6, this->_internal_eye_color(), target);
  }

  // int32 eyebrow_color = 7;
  if (this->_internal_eyebrow_color() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt32ToArray(7, this->_internal_eyebrow_color(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:Protocol.SCharacterAppearance)
  return target;
}

size_t SCharacterAppearance::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:Protocol.SCharacterAppearance)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // .Protocol.ERace race = 1;
  if (this->_internal_race() != 0) {
    total_size += 1 +
      ::_pbi::WireFormatLite::EnumSize(this->_internal_race());
  }

  // .Protocol.ECharacterClass character_class = 2;
  if (this->_internal_character_class() != 0) {
    total_size += 1 +
      ::_pbi::WireFormatLite::EnumSize(this->_internal_character_class());
  }

  // int32 seat = 3;
  if (this->_internal_seat() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(this->_internal_seat());
  }

  // int32 skin_color = 4;
  if (this->_internal_skin_color() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(this->_internal_skin_color());
  }

  // int32 hair_color = 5;
  if (this->_internal_hair_color() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(this->_internal_hair_color());
  }

  // int32 eye_color = 6;
  if (this->_internal_eye_color() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(this->_internal_eye_color());
  }

  // int32 eyebrow_color = 7;
  if (this->_internal_eyebrow_color() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(this->_internal_eyebrow_color());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData SCharacterAppearance::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    SCharacterAppearance::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*SCharacterAppearance::GetClassData() const { return &_class_data_; }


void SCharacterAppearance::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<SCharacterAppearance*>(&to_msg);
  auto& from = static_cast<const SCharacterAppearance&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:Protocol.SCharacterAppearance)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_race() != 0) {
    _this->_internal_set_race(from._internal_race());
  }
  if (from._internal_character_class() != 0) {
    _this->_internal_set_character_class(from._internal_character_class());
  }
  if (from._internal_seat() != 0) {
    _this->_internal_set_seat(from._internal_seat());
  }
  if (from._internal_skin_color() != 0) {
    _this->_internal_set_skin_color(from._internal_skin_color());
  }
  if (from._internal_hair_color() != 0) {
    _this->_internal_set_hair_color(from._internal_hair_color());
  }
  if (from._internal_eye_color() != 0) {
    _this->_internal_set_eye_color(from._internal_eye_color());
  }
  if (from._internal_eyebrow_color() != 0) {
    _this->_internal_set_eyebrow_color(from._internal_eyebrow_color());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void SCharacterAppearance::CopyFrom(const SCharacterAppearance& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:Protocol.SCharacterAppearance)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool SCharacterAppearance::IsInitialized() const {
  return true;
}

void SCharacterAppearance::InternalSwap(SCharacterAppearance* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(SCharacterAppearance, _impl_.eyebrow_color_)
      + sizeof(SCharacterAppearance::_impl_.eyebrow_color_)
      - PROTOBUF_FIELD_OFFSET(SCharacterAppearance, _impl_.race_)>(
          reinterpret_cast<char*>(&_impl_.race_),
          reinterpret_cast<char*>(&other->_impl_.race_));
}

::PROTOBUF_NAMESPACE_ID::Metadata SCharacterAppearance::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_PacketStruct_2eproto_getter, &descriptor_table_PacketStruct_2eproto_once,
      file_level_metadata_PacketStruct_2eproto[0]);
}

// ===================================================================

class SCharacterEqipment::_Internal {
 public:
};

SCharacterEqipment::SCharacterEqipment(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:Protocol.SCharacterEqipment)
}
SCharacterEqipment::SCharacterEqipment(const SCharacterEqipment& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  SCharacterEqipment* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.hair_){}
    , decltype(_impl_.helmet_){}
    , decltype(_impl_.shoulders_){}
    , decltype(_impl_.chest_add_){}
    , decltype(_impl_.bracers_add_){}
    , decltype(_impl_.hands_add_){}
    , decltype(_impl_.pants_add_){}
    , decltype(_impl_.boots_){}
    , decltype(_impl_.weapon_l_){}
    , decltype(_impl_.weapon_r_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::memcpy(&_impl_.hair_, &from._impl_.hair_,
    static_cast<size_t>(reinterpret_cast<char*>(&_impl_.weapon_r_) -
    reinterpret_cast<char*>(&_impl_.hair_)) + sizeof(_impl_.weapon_r_));
  // @@protoc_insertion_point(copy_constructor:Protocol.SCharacterEqipment)
}

inline void SCharacterEqipment::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.hair_){0}
    , decltype(_impl_.helmet_){0}
    , decltype(_impl_.shoulders_){0}
    , decltype(_impl_.chest_add_){0}
    , decltype(_impl_.bracers_add_){0}
    , decltype(_impl_.hands_add_){0}
    , decltype(_impl_.pants_add_){0}
    , decltype(_impl_.boots_){0}
    , decltype(_impl_.weapon_l_){0}
    , decltype(_impl_.weapon_r_){0}
    , /*decltype(_impl_._cached_size_)*/{}
  };
}

SCharacterEqipment::~SCharacterEqipment() {
  // @@protoc_insertion_point(destructor:Protocol.SCharacterEqipment)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void SCharacterEqipment::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
}

void SCharacterEqipment::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void SCharacterEqipment::Clear() {
// @@protoc_insertion_point(message_clear_start:Protocol.SCharacterEqipment)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::memset(&_impl_.hair_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&_impl_.weapon_r_) -
      reinterpret_cast<char*>(&_impl_.hair_)) + sizeof(_impl_.weapon_r_));
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* SCharacterEqipment::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // int32 hair = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          _impl_.hair_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // int32 helmet = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 16)) {
          _impl_.helmet_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // int32 shoulders = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 24)) {
          _impl_.shoulders_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // int32 chest_add = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 32)) {
          _impl_.chest_add_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // int32 bracers_add = 5;
      case 5:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 40)) {
          _impl_.bracers_add_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // int32 hands_add = 6;
      case 6:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 48)) {
          _impl_.hands_add_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // int32 pants_add = 7;
      case 7:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 56)) {
          _impl_.pants_add_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // int32 boots = 8;
      case 8:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 64)) {
          _impl_.boots_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // int32 weapon_l = 9;
      case 9:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 72)) {
          _impl_.weapon_l_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // int32 weapon_r = 10;
      case 10:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 80)) {
          _impl_.weapon_r_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* SCharacterEqipment::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:Protocol.SCharacterEqipment)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // int32 hair = 1;
  if (this->_internal_hair() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt32ToArray(1, this->_internal_hair(), target);
  }

  // int32 helmet = 2;
  if (this->_internal_helmet() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt32ToArray(2, this->_internal_helmet(), target);
  }

  // int32 shoulders = 3;
  if (this->_internal_shoulders() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt32ToArray(3, this->_internal_shoulders(), target);
  }

  // int32 chest_add = 4;
  if (this->_internal_chest_add() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt32ToArray(4, this->_internal_chest_add(), target);
  }

  // int32 bracers_add = 5;
  if (this->_internal_bracers_add() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt32ToArray(5, this->_internal_bracers_add(), target);
  }

  // int32 hands_add = 6;
  if (this->_internal_hands_add() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt32ToArray(6, this->_internal_hands_add(), target);
  }

  // int32 pants_add = 7;
  if (this->_internal_pants_add() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt32ToArray(7, this->_internal_pants_add(), target);
  }

  // int32 boots = 8;
  if (this->_internal_boots() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt32ToArray(8, this->_internal_boots(), target);
  }

  // int32 weapon_l = 9;
  if (this->_internal_weapon_l() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt32ToArray(9, this->_internal_weapon_l(), target);
  }

  // int32 weapon_r = 10;
  if (this->_internal_weapon_r() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt32ToArray(10, this->_internal_weapon_r(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:Protocol.SCharacterEqipment)
  return target;
}

size_t SCharacterEqipment::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:Protocol.SCharacterEqipment)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // int32 hair = 1;
  if (this->_internal_hair() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(this->_internal_hair());
  }

  // int32 helmet = 2;
  if (this->_internal_helmet() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(this->_internal_helmet());
  }

  // int32 shoulders = 3;
  if (this->_internal_shoulders() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(this->_internal_shoulders());
  }

  // int32 chest_add = 4;
  if (this->_internal_chest_add() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(this->_internal_chest_add());
  }

  // int32 bracers_add = 5;
  if (this->_internal_bracers_add() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(this->_internal_bracers_add());
  }

  // int32 hands_add = 6;
  if (this->_internal_hands_add() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(this->_internal_hands_add());
  }

  // int32 pants_add = 7;
  if (this->_internal_pants_add() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(this->_internal_pants_add());
  }

  // int32 boots = 8;
  if (this->_internal_boots() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(this->_internal_boots());
  }

  // int32 weapon_l = 9;
  if (this->_internal_weapon_l() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(this->_internal_weapon_l());
  }

  // int32 weapon_r = 10;
  if (this->_internal_weapon_r() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(this->_internal_weapon_r());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData SCharacterEqipment::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    SCharacterEqipment::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*SCharacterEqipment::GetClassData() const { return &_class_data_; }


void SCharacterEqipment::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<SCharacterEqipment*>(&to_msg);
  auto& from = static_cast<const SCharacterEqipment&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:Protocol.SCharacterEqipment)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_hair() != 0) {
    _this->_internal_set_hair(from._internal_hair());
  }
  if (from._internal_helmet() != 0) {
    _this->_internal_set_helmet(from._internal_helmet());
  }
  if (from._internal_shoulders() != 0) {
    _this->_internal_set_shoulders(from._internal_shoulders());
  }
  if (from._internal_chest_add() != 0) {
    _this->_internal_set_chest_add(from._internal_chest_add());
  }
  if (from._internal_bracers_add() != 0) {
    _this->_internal_set_bracers_add(from._internal_bracers_add());
  }
  if (from._internal_hands_add() != 0) {
    _this->_internal_set_hands_add(from._internal_hands_add());
  }
  if (from._internal_pants_add() != 0) {
    _this->_internal_set_pants_add(from._internal_pants_add());
  }
  if (from._internal_boots() != 0) {
    _this->_internal_set_boots(from._internal_boots());
  }
  if (from._internal_weapon_l() != 0) {
    _this->_internal_set_weapon_l(from._internal_weapon_l());
  }
  if (from._internal_weapon_r() != 0) {
    _this->_internal_set_weapon_r(from._internal_weapon_r());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void SCharacterEqipment::CopyFrom(const SCharacterEqipment& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:Protocol.SCharacterEqipment)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool SCharacterEqipment::IsInitialized() const {
  return true;
}

void SCharacterEqipment::InternalSwap(SCharacterEqipment* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(SCharacterEqipment, _impl_.weapon_r_)
      + sizeof(SCharacterEqipment::_impl_.weapon_r_)
      - PROTOBUF_FIELD_OFFSET(SCharacterEqipment, _impl_.hair_)>(
          reinterpret_cast<char*>(&_impl_.hair_),
          reinterpret_cast<char*>(&other->_impl_.hair_));
}

::PROTOBUF_NAMESPACE_ID::Metadata SCharacterEqipment::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_PacketStruct_2eproto_getter, &descriptor_table_PacketStruct_2eproto_once,
      file_level_metadata_PacketStruct_2eproto[1]);
}

// @@protoc_insertion_point(namespace_scope)
}  // namespace Protocol
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::Protocol::SCharacterAppearance*
Arena::CreateMaybeMessage< ::Protocol::SCharacterAppearance >(Arena* arena) {
  return Arena::CreateMessageInternal< ::Protocol::SCharacterAppearance >(arena);
}
template<> PROTOBUF_NOINLINE ::Protocol::SCharacterEqipment*
Arena::CreateMaybeMessage< ::Protocol::SCharacterEqipment >(Arena* arena) {
  return Arena::CreateMessageInternal< ::Protocol::SCharacterEqipment >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
