#if defined(_MSC_VER)
        #pragma warning (disable:4018) // 'expression' : signed/unsigned mismatch
        #pragma warning (disable:4065) // switch statement contains 'default' but no 'case' labels
        #pragma warning (disable:4146) // unary minus operator applied to unsigned type, result still unsigned
        #pragma warning (disable:4244) // 'conversion' conversion from 'type1' to 'type2', possible loss of data
        #pragma warning (disable:4251) // 'identifier' : class 'type' needs to have dll-interface to be used byclient of class 'type2'
        #pragma warning (disable:4267) // 'var' : conversion from 'size_t' to 'type', possible loss of data
        #pragma warning (disable:4305) // 'identifier' : truncation from 'type1' to 'type2'
        #pragma warning (disable:4307) // 'operator' : integral constant overflow
        #pragma warning (disable:4309) // 'conversion' : truncation of constant value
        #pragma warning (disable:4334) // 'operator' : result of 32-bit shift implicitly converted to 64 bits (was64bit shift intended?)
        #pragma warning (disable:4355) // 'this' : used in base member initializer list
        #pragma warning (disable:4506) // no definition for inline function 'function'
        #pragma warning (disable:4800) // 'type' : forcing value to bool 'true' or 'false' (performance warning)
		 #pragma warning (disable:4946) // reinterpret_cast used between related classes: 'class1' and 'class2'
        #pragma warning (disable:4996) // The compiler encountered a deprecated declaration.
        #pragma warning (disable:4125) // decimal digit terminates octal escape sequence
#endif

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: DungeonPacket.proto

#include "DungeonPacket.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG

namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = _pb::internal;

namespace Protocol {
PROTOBUF_CONSTEXPR C2S_EnterDungeon::C2S_EnterDungeon(
    ::_pbi::ConstantInitialized) {}
struct C2S_EnterDungeonDefaultTypeInternal {
  PROTOBUF_CONSTEXPR C2S_EnterDungeonDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~C2S_EnterDungeonDefaultTypeInternal() {}
  union {
    C2S_EnterDungeon _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 C2S_EnterDungeonDefaultTypeInternal _C2S_EnterDungeon_default_instance_;
PROTOBUF_CONSTEXPR S2C_EnterDungeon::S2C_EnterDungeon(
    ::_pbi::ConstantInitialized) {}
struct S2C_EnterDungeonDefaultTypeInternal {
  PROTOBUF_CONSTEXPR S2C_EnterDungeonDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~S2C_EnterDungeonDefaultTypeInternal() {}
  union {
    S2C_EnterDungeon _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 S2C_EnterDungeonDefaultTypeInternal _S2C_EnterDungeon_default_instance_;
}  // namespace Protocol
static ::_pb::Metadata file_level_metadata_DungeonPacket_2eproto[2];
static constexpr ::_pb::EnumDescriptor const** file_level_enum_descriptors_DungeonPacket_2eproto = nullptr;
static constexpr ::_pb::ServiceDescriptor const** file_level_service_descriptors_DungeonPacket_2eproto = nullptr;

const uint32_t TableStruct_DungeonPacket_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::Protocol::C2S_EnterDungeon, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::Protocol::S2C_EnterDungeon, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
};
static const ::_pbi::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, -1, sizeof(::Protocol::C2S_EnterDungeon)},
  { 6, -1, -1, sizeof(::Protocol::S2C_EnterDungeon)},
};

static const ::_pb::Message* const file_default_instances[] = {
  &::Protocol::_C2S_EnterDungeon_default_instance_._instance,
  &::Protocol::_S2C_EnterDungeon_default_instance_._instance,
};

const char descriptor_table_protodef_DungeonPacket_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\023DungeonPacket.proto\022\010Protocol\"\022\n\020C2S_E"
  "nterDungeon\"\022\n\020S2C_EnterDungeonb\006proto3"
  ;
static ::_pbi::once_flag descriptor_table_DungeonPacket_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_DungeonPacket_2eproto = {
    false, false, 79, descriptor_table_protodef_DungeonPacket_2eproto,
    "DungeonPacket.proto",
    &descriptor_table_DungeonPacket_2eproto_once, nullptr, 0, 2,
    schemas, file_default_instances, TableStruct_DungeonPacket_2eproto::offsets,
    file_level_metadata_DungeonPacket_2eproto, file_level_enum_descriptors_DungeonPacket_2eproto,
    file_level_service_descriptors_DungeonPacket_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_DungeonPacket_2eproto_getter() {
  return &descriptor_table_DungeonPacket_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_DungeonPacket_2eproto(&descriptor_table_DungeonPacket_2eproto);
namespace Protocol {

// ===================================================================

class C2S_EnterDungeon::_Internal {
 public:
};

C2S_EnterDungeon::C2S_EnterDungeon(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase(arena, is_message_owned) {
  // @@protoc_insertion_point(arena_constructor:Protocol.C2S_EnterDungeon)
}
C2S_EnterDungeon::C2S_EnterDungeon(const C2S_EnterDungeon& from)
  : ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase() {
  C2S_EnterDungeon* const _this = this; (void)_this;
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  // @@protoc_insertion_point(copy_constructor:Protocol.C2S_EnterDungeon)
}





const ::PROTOBUF_NAMESPACE_ID::Message::ClassData C2S_EnterDungeon::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase::CopyImpl,
    ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase::MergeImpl,
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*C2S_EnterDungeon::GetClassData() const { return &_class_data_; }







::PROTOBUF_NAMESPACE_ID::Metadata C2S_EnterDungeon::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_DungeonPacket_2eproto_getter, &descriptor_table_DungeonPacket_2eproto_once,
      file_level_metadata_DungeonPacket_2eproto[0]);
}

// ===================================================================

class S2C_EnterDungeon::_Internal {
 public:
};

S2C_EnterDungeon::S2C_EnterDungeon(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase(arena, is_message_owned) {
  // @@protoc_insertion_point(arena_constructor:Protocol.S2C_EnterDungeon)
}
S2C_EnterDungeon::S2C_EnterDungeon(const S2C_EnterDungeon& from)
  : ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase() {
  S2C_EnterDungeon* const _this = this; (void)_this;
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  // @@protoc_insertion_point(copy_constructor:Protocol.S2C_EnterDungeon)
}





const ::PROTOBUF_NAMESPACE_ID::Message::ClassData S2C_EnterDungeon::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase::CopyImpl,
    ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase::MergeImpl,
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*S2C_EnterDungeon::GetClassData() const { return &_class_data_; }







::PROTOBUF_NAMESPACE_ID::Metadata S2C_EnterDungeon::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_DungeonPacket_2eproto_getter, &descriptor_table_DungeonPacket_2eproto_once,
      file_level_metadata_DungeonPacket_2eproto[1]);
}

// @@protoc_insertion_point(namespace_scope)
}  // namespace Protocol
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::Protocol::C2S_EnterDungeon*
Arena::CreateMaybeMessage< ::Protocol::C2S_EnterDungeon >(Arena* arena) {
  return Arena::CreateMessageInternal< ::Protocol::C2S_EnterDungeon >(arena);
}
template<> PROTOBUF_NOINLINE ::Protocol::S2C_EnterDungeon*
Arena::CreateMaybeMessage< ::Protocol::S2C_EnterDungeon >(Arena* arena) {
  return Arena::CreateMessageInternal< ::Protocol::S2C_EnterDungeon >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
