#if defined(_MSC_VER)
        #pragma warning (disable:4018) // 'expression' : signed/unsigned mismatch
        #pragma warning (disable:4065) // switch statement contains 'default' but no 'case' labels
        #pragma warning (disable:4146) // unary minus operator applied to unsigned type, result still unsigned
        #pragma warning (disable:4244) // 'conversion' conversion from 'type1' to 'type2', possible loss of data
        #pragma warning (disable:4251) // 'identifier' : class 'type' needs to have dll-interface to be used byclient of class 'type2'
        #pragma warning (disable:4267) // 'var' : conversion from 'size_t' to 'type', possible loss of data
        #pragma warning (disable:4305) // 'identifier' : truncation from 'type1' to 'type2'
        #pragma warning (disable:4307) // 'operator' : integral constant overflow
        #pragma warning (disable:4309) // 'conversion' : truncation of constant value
        #pragma warning (disable:4334) // 'operator' : result of 32-bit shift implicitly converted to 64 bits (was64bit shift intended?)
        #pragma warning (disable:4355) // 'this' : used in base member initializer list
        #pragma warning (disable:4506) // no definition for inline function 'function'
        #pragma warning (disable:4800) // 'type' : forcing value to bool 'true' or 'false' (performance warning)
		 #pragma warning (disable:4946) // reinterpret_cast used between related classes: 'class1' and 'class2'
        #pragma warning (disable:4996) // The compiler encountered a deprecated declaration.
        #pragma warning (disable:4125) // decimal digit terminates octal escape sequence
#endif

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: GamePacket.proto

#include "GamePacket.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG

namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = _pb::internal;

namespace Protocol {
PROTOBUF_CONSTEXPR C2S_EnterGameServer::C2S_EnterGameServer(
    ::_pbi::ConstantInitialized) {}
struct C2S_EnterGameServerDefaultTypeInternal {
  PROTOBUF_CONSTEXPR C2S_EnterGameServerDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~C2S_EnterGameServerDefaultTypeInternal() {}
  union {
    C2S_EnterGameServer _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 C2S_EnterGameServerDefaultTypeInternal _C2S_EnterGameServer_default_instance_;
PROTOBUF_CONSTEXPR S2C_EnterGameServer::S2C_EnterGameServer(
    ::_pbi::ConstantInitialized) {}
struct S2C_EnterGameServerDefaultTypeInternal {
  PROTOBUF_CONSTEXPR S2C_EnterGameServerDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~S2C_EnterGameServerDefaultTypeInternal() {}
  union {
    S2C_EnterGameServer _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 S2C_EnterGameServerDefaultTypeInternal _S2C_EnterGameServer_default_instance_;
PROTOBUF_CONSTEXPR C2S_LeaveGameServer::C2S_LeaveGameServer(
    ::_pbi::ConstantInitialized) {}
struct C2S_LeaveGameServerDefaultTypeInternal {
  PROTOBUF_CONSTEXPR C2S_LeaveGameServerDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~C2S_LeaveGameServerDefaultTypeInternal() {}
  union {
    C2S_LeaveGameServer _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 C2S_LeaveGameServerDefaultTypeInternal _C2S_LeaveGameServer_default_instance_;
PROTOBUF_CONSTEXPR S2C_LeaveGameServer::S2C_LeaveGameServer(
    ::_pbi::ConstantInitialized) {}
struct S2C_LeaveGameServerDefaultTypeInternal {
  PROTOBUF_CONSTEXPR S2C_LeaveGameServerDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~S2C_LeaveGameServerDefaultTypeInternal() {}
  union {
    S2C_LeaveGameServer _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 S2C_LeaveGameServerDefaultTypeInternal _S2C_LeaveGameServer_default_instance_;
PROTOBUF_CONSTEXPR C2S_MovementCharacter::C2S_MovementCharacter(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.transform_)*/nullptr
  , /*decltype(_impl_.timestamp_)*/int64_t{0}
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct C2S_MovementCharacterDefaultTypeInternal {
  PROTOBUF_CONSTEXPR C2S_MovementCharacterDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~C2S_MovementCharacterDefaultTypeInternal() {}
  union {
    C2S_MovementCharacter _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 C2S_MovementCharacterDefaultTypeInternal _C2S_MovementCharacter_default_instance_;
PROTOBUF_CONSTEXPR S2C_MovementCharacter::S2C_MovementCharacter(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.transform_)*/nullptr
  , /*decltype(_impl_.remoteid_)*/int64_t{0}
  , /*decltype(_impl_.timestamp_)*/int64_t{0}
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct S2C_MovementCharacterDefaultTypeInternal {
  PROTOBUF_CONSTEXPR S2C_MovementCharacterDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~S2C_MovementCharacterDefaultTypeInternal() {}
  union {
    S2C_MovementCharacter _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 S2C_MovementCharacterDefaultTypeInternal _S2C_MovementCharacter_default_instance_;
}  // namespace Protocol
static ::_pb::Metadata file_level_metadata_GamePacket_2eproto[6];
static constexpr ::_pb::EnumDescriptor const** file_level_enum_descriptors_GamePacket_2eproto = nullptr;
static constexpr ::_pb::ServiceDescriptor const** file_level_service_descriptors_GamePacket_2eproto = nullptr;

const uint32_t TableStruct_GamePacket_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::Protocol::C2S_EnterGameServer, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::Protocol::S2C_EnterGameServer, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::Protocol::C2S_LeaveGameServer, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::Protocol::S2C_LeaveGameServer, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::Protocol::C2S_MovementCharacter, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::Protocol::C2S_MovementCharacter, _impl_.timestamp_),
  PROTOBUF_FIELD_OFFSET(::Protocol::C2S_MovementCharacter, _impl_.transform_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::Protocol::S2C_MovementCharacter, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::Protocol::S2C_MovementCharacter, _impl_.remoteid_),
  PROTOBUF_FIELD_OFFSET(::Protocol::S2C_MovementCharacter, _impl_.timestamp_),
  PROTOBUF_FIELD_OFFSET(::Protocol::S2C_MovementCharacter, _impl_.transform_),
};
static const ::_pbi::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, -1, sizeof(::Protocol::C2S_EnterGameServer)},
  { 6, -1, -1, sizeof(::Protocol::S2C_EnterGameServer)},
  { 12, -1, -1, sizeof(::Protocol::C2S_LeaveGameServer)},
  { 18, -1, -1, sizeof(::Protocol::S2C_LeaveGameServer)},
  { 24, -1, -1, sizeof(::Protocol::C2S_MovementCharacter)},
  { 32, -1, -1, sizeof(::Protocol::S2C_MovementCharacter)},
};

static const ::_pb::Message* const file_default_instances[] = {
  &::Protocol::_C2S_EnterGameServer_default_instance_._instance,
  &::Protocol::_S2C_EnterGameServer_default_instance_._instance,
  &::Protocol::_C2S_LeaveGameServer_default_instance_._instance,
  &::Protocol::_S2C_LeaveGameServer_default_instance_._instance,
  &::Protocol::_C2S_MovementCharacter_default_instance_._instance,
  &::Protocol::_S2C_MovementCharacter_default_instance_._instance,
};

const char descriptor_table_protodef_GamePacket_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\020GamePacket.proto\022\010Protocol\032\022PacketStru"
  "ct.proto\"\025\n\023C2S_EnterGameServer\"\025\n\023S2C_E"
  "nterGameServer\"\025\n\023C2S_LeaveGameServer\"\025\n"
  "\023S2C_LeaveGameServer\"S\n\025C2S_MovementChar"
  "acter\022\021\n\ttimestamp\030\001 \001(\003\022\'\n\ttransform\030\002 "
  "\001(\0132\024.Protocol.STransform\"e\n\025S2C_Movemen"
  "tCharacter\022\020\n\010remoteID\030\001 \001(\003\022\021\n\ttimestam"
  "p\030\002 \001(\003\022\'\n\ttransform\030\003 \001(\0132\024.Protocol.ST"
  "ransformb\006proto3"
  ;
static const ::_pbi::DescriptorTable* const descriptor_table_GamePacket_2eproto_deps[1] = {
  &::descriptor_table_PacketStruct_2eproto,
};
static ::_pbi::once_flag descriptor_table_GamePacket_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_GamePacket_2eproto = {
    false, false, 336, descriptor_table_protodef_GamePacket_2eproto,
    "GamePacket.proto",
    &descriptor_table_GamePacket_2eproto_once, descriptor_table_GamePacket_2eproto_deps, 1, 6,
    schemas, file_default_instances, TableStruct_GamePacket_2eproto::offsets,
    file_level_metadata_GamePacket_2eproto, file_level_enum_descriptors_GamePacket_2eproto,
    file_level_service_descriptors_GamePacket_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_GamePacket_2eproto_getter() {
  return &descriptor_table_GamePacket_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_GamePacket_2eproto(&descriptor_table_GamePacket_2eproto);
namespace Protocol {

// ===================================================================

class C2S_EnterGameServer::_Internal {
 public:
};

C2S_EnterGameServer::C2S_EnterGameServer(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase(arena, is_message_owned) {
  // @@protoc_insertion_point(arena_constructor:Protocol.C2S_EnterGameServer)
}
C2S_EnterGameServer::C2S_EnterGameServer(const C2S_EnterGameServer& from)
  : ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase() {
  C2S_EnterGameServer* const _this = this; (void)_this;
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  // @@protoc_insertion_point(copy_constructor:Protocol.C2S_EnterGameServer)
}





const ::PROTOBUF_NAMESPACE_ID::Message::ClassData C2S_EnterGameServer::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase::CopyImpl,
    ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase::MergeImpl,
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*C2S_EnterGameServer::GetClassData() const { return &_class_data_; }







::PROTOBUF_NAMESPACE_ID::Metadata C2S_EnterGameServer::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_GamePacket_2eproto_getter, &descriptor_table_GamePacket_2eproto_once,
      file_level_metadata_GamePacket_2eproto[0]);
}

// ===================================================================

class S2C_EnterGameServer::_Internal {
 public:
};

S2C_EnterGameServer::S2C_EnterGameServer(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase(arena, is_message_owned) {
  // @@protoc_insertion_point(arena_constructor:Protocol.S2C_EnterGameServer)
}
S2C_EnterGameServer::S2C_EnterGameServer(const S2C_EnterGameServer& from)
  : ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase() {
  S2C_EnterGameServer* const _this = this; (void)_this;
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  // @@protoc_insertion_point(copy_constructor:Protocol.S2C_EnterGameServer)
}





const ::PROTOBUF_NAMESPACE_ID::Message::ClassData S2C_EnterGameServer::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase::CopyImpl,
    ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase::MergeImpl,
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*S2C_EnterGameServer::GetClassData() const { return &_class_data_; }







::PROTOBUF_NAMESPACE_ID::Metadata S2C_EnterGameServer::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_GamePacket_2eproto_getter, &descriptor_table_GamePacket_2eproto_once,
      file_level_metadata_GamePacket_2eproto[1]);
}

// ===================================================================

class C2S_LeaveGameServer::_Internal {
 public:
};

C2S_LeaveGameServer::C2S_LeaveGameServer(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase(arena, is_message_owned) {
  // @@protoc_insertion_point(arena_constructor:Protocol.C2S_LeaveGameServer)
}
C2S_LeaveGameServer::C2S_LeaveGameServer(const C2S_LeaveGameServer& from)
  : ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase() {
  C2S_LeaveGameServer* const _this = this; (void)_this;
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  // @@protoc_insertion_point(copy_constructor:Protocol.C2S_LeaveGameServer)
}





const ::PROTOBUF_NAMESPACE_ID::Message::ClassData C2S_LeaveGameServer::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase::CopyImpl,
    ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase::MergeImpl,
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*C2S_LeaveGameServer::GetClassData() const { return &_class_data_; }







::PROTOBUF_NAMESPACE_ID::Metadata C2S_LeaveGameServer::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_GamePacket_2eproto_getter, &descriptor_table_GamePacket_2eproto_once,
      file_level_metadata_GamePacket_2eproto[2]);
}

// ===================================================================

class S2C_LeaveGameServer::_Internal {
 public:
};

S2C_LeaveGameServer::S2C_LeaveGameServer(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase(arena, is_message_owned) {
  // @@protoc_insertion_point(arena_constructor:Protocol.S2C_LeaveGameServer)
}
S2C_LeaveGameServer::S2C_LeaveGameServer(const S2C_LeaveGameServer& from)
  : ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase() {
  S2C_LeaveGameServer* const _this = this; (void)_this;
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  // @@protoc_insertion_point(copy_constructor:Protocol.S2C_LeaveGameServer)
}





const ::PROTOBUF_NAMESPACE_ID::Message::ClassData S2C_LeaveGameServer::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase::CopyImpl,
    ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase::MergeImpl,
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*S2C_LeaveGameServer::GetClassData() const { return &_class_data_; }







::PROTOBUF_NAMESPACE_ID::Metadata S2C_LeaveGameServer::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_GamePacket_2eproto_getter, &descriptor_table_GamePacket_2eproto_once,
      file_level_metadata_GamePacket_2eproto[3]);
}

// ===================================================================

class C2S_MovementCharacter::_Internal {
 public:
  static const ::Protocol::STransform& transform(const C2S_MovementCharacter* msg);
};

const ::Protocol::STransform&
C2S_MovementCharacter::_Internal::transform(const C2S_MovementCharacter* msg) {
  return *msg->_impl_.transform_;
}
void C2S_MovementCharacter::clear_transform() {
  if (GetArenaForAllocation() == nullptr && _impl_.transform_ != nullptr) {
    delete _impl_.transform_;
  }
  _impl_.transform_ = nullptr;
}
C2S_MovementCharacter::C2S_MovementCharacter(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:Protocol.C2S_MovementCharacter)
}
C2S_MovementCharacter::C2S_MovementCharacter(const C2S_MovementCharacter& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  C2S_MovementCharacter* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.transform_){nullptr}
    , decltype(_impl_.timestamp_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  if (from._internal_has_transform()) {
    _this->_impl_.transform_ = new ::Protocol::STransform(*from._impl_.transform_);
  }
  _this->_impl_.timestamp_ = from._impl_.timestamp_;
  // @@protoc_insertion_point(copy_constructor:Protocol.C2S_MovementCharacter)
}

inline void C2S_MovementCharacter::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.transform_){nullptr}
    , decltype(_impl_.timestamp_){int64_t{0}}
    , /*decltype(_impl_._cached_size_)*/{}
  };
}

C2S_MovementCharacter::~C2S_MovementCharacter() {
  // @@protoc_insertion_point(destructor:Protocol.C2S_MovementCharacter)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void C2S_MovementCharacter::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  if (this != internal_default_instance()) delete _impl_.transform_;
}

void C2S_MovementCharacter::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void C2S_MovementCharacter::Clear() {
// @@protoc_insertion_point(message_clear_start:Protocol.C2S_MovementCharacter)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  if (GetArenaForAllocation() == nullptr && _impl_.transform_ != nullptr) {
    delete _impl_.transform_;
  }
  _impl_.transform_ = nullptr;
  _impl_.timestamp_ = int64_t{0};
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* C2S_MovementCharacter::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // int64 timestamp = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          _impl_.timestamp_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // .Protocol.STransform transform = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 18)) {
          ptr = ctx->ParseMessage(_internal_mutable_transform(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* C2S_MovementCharacter::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:Protocol.C2S_MovementCharacter)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // int64 timestamp = 1;
  if (this->_internal_timestamp() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt64ToArray(1, this->_internal_timestamp(), target);
  }

  // .Protocol.STransform transform = 2;
  if (this->_internal_has_transform()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(2, _Internal::transform(this),
        _Internal::transform(this).GetCachedSize(), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:Protocol.C2S_MovementCharacter)
  return target;
}

size_t C2S_MovementCharacter::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:Protocol.C2S_MovementCharacter)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // .Protocol.STransform transform = 2;
  if (this->_internal_has_transform()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *_impl_.transform_);
  }

  // int64 timestamp = 1;
  if (this->_internal_timestamp() != 0) {
    total_size += ::_pbi::WireFormatLite::Int64SizePlusOne(this->_internal_timestamp());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData C2S_MovementCharacter::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    C2S_MovementCharacter::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*C2S_MovementCharacter::GetClassData() const { return &_class_data_; }


void C2S_MovementCharacter::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<C2S_MovementCharacter*>(&to_msg);
  auto& from = static_cast<const C2S_MovementCharacter&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:Protocol.C2S_MovementCharacter)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_has_transform()) {
    _this->_internal_mutable_transform()->::Protocol::STransform::MergeFrom(
        from._internal_transform());
  }
  if (from._internal_timestamp() != 0) {
    _this->_internal_set_timestamp(from._internal_timestamp());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void C2S_MovementCharacter::CopyFrom(const C2S_MovementCharacter& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:Protocol.C2S_MovementCharacter)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool C2S_MovementCharacter::IsInitialized() const {
  return true;
}

void C2S_MovementCharacter::InternalSwap(C2S_MovementCharacter* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(C2S_MovementCharacter, _impl_.timestamp_)
      + sizeof(C2S_MovementCharacter::_impl_.timestamp_)
      - PROTOBUF_FIELD_OFFSET(C2S_MovementCharacter, _impl_.transform_)>(
          reinterpret_cast<char*>(&_impl_.transform_),
          reinterpret_cast<char*>(&other->_impl_.transform_));
}

::PROTOBUF_NAMESPACE_ID::Metadata C2S_MovementCharacter::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_GamePacket_2eproto_getter, &descriptor_table_GamePacket_2eproto_once,
      file_level_metadata_GamePacket_2eproto[4]);
}

// ===================================================================

class S2C_MovementCharacter::_Internal {
 public:
  static const ::Protocol::STransform& transform(const S2C_MovementCharacter* msg);
};

const ::Protocol::STransform&
S2C_MovementCharacter::_Internal::transform(const S2C_MovementCharacter* msg) {
  return *msg->_impl_.transform_;
}
void S2C_MovementCharacter::clear_transform() {
  if (GetArenaForAllocation() == nullptr && _impl_.transform_ != nullptr) {
    delete _impl_.transform_;
  }
  _impl_.transform_ = nullptr;
}
S2C_MovementCharacter::S2C_MovementCharacter(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:Protocol.S2C_MovementCharacter)
}
S2C_MovementCharacter::S2C_MovementCharacter(const S2C_MovementCharacter& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  S2C_MovementCharacter* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.transform_){nullptr}
    , decltype(_impl_.remoteid_){}
    , decltype(_impl_.timestamp_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  if (from._internal_has_transform()) {
    _this->_impl_.transform_ = new ::Protocol::STransform(*from._impl_.transform_);
  }
  ::memcpy(&_impl_.remoteid_, &from._impl_.remoteid_,
    static_cast<size_t>(reinterpret_cast<char*>(&_impl_.timestamp_) -
    reinterpret_cast<char*>(&_impl_.remoteid_)) + sizeof(_impl_.timestamp_));
  // @@protoc_insertion_point(copy_constructor:Protocol.S2C_MovementCharacter)
}

inline void S2C_MovementCharacter::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.transform_){nullptr}
    , decltype(_impl_.remoteid_){int64_t{0}}
    , decltype(_impl_.timestamp_){int64_t{0}}
    , /*decltype(_impl_._cached_size_)*/{}
  };
}

S2C_MovementCharacter::~S2C_MovementCharacter() {
  // @@protoc_insertion_point(destructor:Protocol.S2C_MovementCharacter)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void S2C_MovementCharacter::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  if (this != internal_default_instance()) delete _impl_.transform_;
}

void S2C_MovementCharacter::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void S2C_MovementCharacter::Clear() {
// @@protoc_insertion_point(message_clear_start:Protocol.S2C_MovementCharacter)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  if (GetArenaForAllocation() == nullptr && _impl_.transform_ != nullptr) {
    delete _impl_.transform_;
  }
  _impl_.transform_ = nullptr;
  ::memset(&_impl_.remoteid_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&_impl_.timestamp_) -
      reinterpret_cast<char*>(&_impl_.remoteid_)) + sizeof(_impl_.timestamp_));
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* S2C_MovementCharacter::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // int64 remoteID = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          _impl_.remoteid_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // int64 timestamp = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 16)) {
          _impl_.timestamp_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // .Protocol.STransform transform = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 26)) {
          ptr = ctx->ParseMessage(_internal_mutable_transform(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* S2C_MovementCharacter::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:Protocol.S2C_MovementCharacter)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // int64 remoteID = 1;
  if (this->_internal_remoteid() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt64ToArray(1, this->_internal_remoteid(), target);
  }

  // int64 timestamp = 2;
  if (this->_internal_timestamp() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt64ToArray(2, this->_internal_timestamp(), target);
  }

  // .Protocol.STransform transform = 3;
  if (this->_internal_has_transform()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(3, _Internal::transform(this),
        _Internal::transform(this).GetCachedSize(), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:Protocol.S2C_MovementCharacter)
  return target;
}

size_t S2C_MovementCharacter::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:Protocol.S2C_MovementCharacter)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // .Protocol.STransform transform = 3;
  if (this->_internal_has_transform()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *_impl_.transform_);
  }

  // int64 remoteID = 1;
  if (this->_internal_remoteid() != 0) {
    total_size += ::_pbi::WireFormatLite::Int64SizePlusOne(this->_internal_remoteid());
  }

  // int64 timestamp = 2;
  if (this->_internal_timestamp() != 0) {
    total_size += ::_pbi::WireFormatLite::Int64SizePlusOne(this->_internal_timestamp());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData S2C_MovementCharacter::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    S2C_MovementCharacter::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*S2C_MovementCharacter::GetClassData() const { return &_class_data_; }


void S2C_MovementCharacter::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<S2C_MovementCharacter*>(&to_msg);
  auto& from = static_cast<const S2C_MovementCharacter&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:Protocol.S2C_MovementCharacter)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_has_transform()) {
    _this->_internal_mutable_transform()->::Protocol::STransform::MergeFrom(
        from._internal_transform());
  }
  if (from._internal_remoteid() != 0) {
    _this->_internal_set_remoteid(from._internal_remoteid());
  }
  if (from._internal_timestamp() != 0) {
    _this->_internal_set_timestamp(from._internal_timestamp());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void S2C_MovementCharacter::CopyFrom(const S2C_MovementCharacter& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:Protocol.S2C_MovementCharacter)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool S2C_MovementCharacter::IsInitialized() const {
  return true;
}

void S2C_MovementCharacter::InternalSwap(S2C_MovementCharacter* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(S2C_MovementCharacter, _impl_.timestamp_)
      + sizeof(S2C_MovementCharacter::_impl_.timestamp_)
      - PROTOBUF_FIELD_OFFSET(S2C_MovementCharacter, _impl_.transform_)>(
          reinterpret_cast<char*>(&_impl_.transform_),
          reinterpret_cast<char*>(&other->_impl_.transform_));
}

::PROTOBUF_NAMESPACE_ID::Metadata S2C_MovementCharacter::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_GamePacket_2eproto_getter, &descriptor_table_GamePacket_2eproto_once,
      file_level_metadata_GamePacket_2eproto[5]);
}

// @@protoc_insertion_point(namespace_scope)
}  // namespace Protocol
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::Protocol::C2S_EnterGameServer*
Arena::CreateMaybeMessage< ::Protocol::C2S_EnterGameServer >(Arena* arena) {
  return Arena::CreateMessageInternal< ::Protocol::C2S_EnterGameServer >(arena);
}
template<> PROTOBUF_NOINLINE ::Protocol::S2C_EnterGameServer*
Arena::CreateMaybeMessage< ::Protocol::S2C_EnterGameServer >(Arena* arena) {
  return Arena::CreateMessageInternal< ::Protocol::S2C_EnterGameServer >(arena);
}
template<> PROTOBUF_NOINLINE ::Protocol::C2S_LeaveGameServer*
Arena::CreateMaybeMessage< ::Protocol::C2S_LeaveGameServer >(Arena* arena) {
  return Arena::CreateMessageInternal< ::Protocol::C2S_LeaveGameServer >(arena);
}
template<> PROTOBUF_NOINLINE ::Protocol::S2C_LeaveGameServer*
Arena::CreateMaybeMessage< ::Protocol::S2C_LeaveGameServer >(Arena* arena) {
  return Arena::CreateMessageInternal< ::Protocol::S2C_LeaveGameServer >(arena);
}
template<> PROTOBUF_NOINLINE ::Protocol::C2S_MovementCharacter*
Arena::CreateMaybeMessage< ::Protocol::C2S_MovementCharacter >(Arena* arena) {
  return Arena::CreateMessageInternal< ::Protocol::C2S_MovementCharacter >(arena);
}
template<> PROTOBUF_NOINLINE ::Protocol::S2C_MovementCharacter*
Arena::CreateMaybeMessage< ::Protocol::S2C_MovementCharacter >(Arena* arena) {
  return Arena::CreateMessageInternal< ::Protocol::S2C_MovementCharacter >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
