#pragma once

#define DEFAULT_TICK 100
#define DEFAULT_SYNC_TICK 1000

#define MAX_POSSIBLE_AREA		2000.0f
#define MAX_LOCATION_DISTANCE	50.0f
#define MAX_LOCATION_SYNC_TIME	1000

#define DEFAULT_CHARACTER_CAPSULE_HEIGHT 96.0f
#define DEFAULT_CHARACTER_CAPSULE_RADIUS 42.0f


#define MAX_RESPAWN_ENEMY_TIME		5000

#define ENEMY_STATE_TICK			100
#define IDLE_TO_ROUND_TIME			10000
#define CHASE_TO_RECOVERY_TIME		5000
#define HIT_TO_CHASE_TIME			100
#define DEATH_HEALTH				0.0f